### ISSUE TITLE
Run Website Hueman on localhost error 

### ISSUE THREAD

**Issue by poysithon** [AlxMedia/hueman#125]
Dear AlxMedia Team ,

When I run this website on localhost , it show error like this " Fatal error: Call to undefined function get_header() in C:\wamp\www\hueman-master\index.php on line 1". Please help to resolve it . Thanks you in advance .

Best Regards,
Sithon

**Comment by jaylinski** [comment]
pro tip: run it inside wordpress ;)

**Comment by niyasc** [comment]
This theme is not supposed to work independently. Please ensure that you have a working wordpress installation
