### ISSUE TITLE
No style in sidebar Contact Form 7

### ISSUE THREAD

**Issue by VadymVolos** [AlxMedia/hueman#137]
No style in sidebar Contact Form 7
Hueman Version: 2.2.3

![Image](http://i.piccy.info/i9/671616c008a6696b19b0cabdfd57053d/1444034570/119089/887339/Contact_Form_7_Hueman.png)

**Comment by VadymVolos** [comment]
Work!!!
I wrapped the form in the "div", and wrote the name of the class="themeform"
```
<div class="themeform">
<div>Ваше имя (обязательно)<br />
    [text* your-name] </div>

<div>Ваш e-mail (обязательно)<br />
    [email* your-email] </div>

<div>Сообщение<br />
    [textarea your-message] </div>

<br />
<div>[submit "Отправить"]</div>
</div>
```
![Image 2](
http://i.piccy.info/i9/6c99c5c4ef3af995d10b0f3f47cce7e3/1444037443/68504/887339/Contact_Form_7_Hueman_2.png)

**Comment by AlxMedia** [comment]
Nicely done :-)
