### ISSUE TITLE
Hungarian language

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#37]
Hello!
New hungarian language url:
https://www.transifex.com/projects/p/hueman-theme/language/hu_HU/

KardiWeb

**Comment by frantzz** [comment]
Why did you delete the repo ?

**Comment by KardiWeb** [comment]
Delete... :-1:

**Comment by keunes** [comment]
@AlxMedia Seems the whole language repo got deleted? Any particular reason?
Would be great if you could enlighten us :+1:
