### ISSUE TITLE
IE11 compatibility: Object doesn't support property or method 'from'

### ISSUE THREAD

**Issue by eri-trabiccolo** [AlxMedia/hueman#435]
see https://github.com/presscustomizr/themes-customizer-fmk/issues/26

**Comment by ghost** [comment]
any fix possible ?
trinidad

**Comment by eri-trabiccolo** [comment]
instead of this:
https://github.com/presscustomizr/hueman/blob/dev/assets/global/oldBrowserCompat.js
use this:
https://github.com/presscustomizr/hueman-pro-addons/blob/master/addons/assets/global/oldBrowserCompat.js

**Comment by eri-trabiccolo** [comment]
Did you mean a pr for that?
