### ISSUE TITLE
Theme Shaking While Featured post changes!

### ISSUE THREAD

**Issue by codeslane** [AlxMedia/hueman#436]
@Nikeo Theme again started shaking when the featured post is changing and sidebars scrolls. 
The whole footer shakes on that moment. 

This maybe browser compatibility issue or maybe a bug. 
I'm using Google Chrome ( up-to-date ).
Site Link: https://www.codeslane.com

Problem is only with non-boxed layout. 
Let me know if you got this. 

Thanks.

Regards,
-Vaibhav Singh

**Comment by ghost** [comment]
Hi @codeslane it looks good on chrome for me. No shaking effect.
Can you try to take a screencast of the problem ( with a free [screencast online service](https://www.google.com/search?q=screencast%20online%20service&rct=j) for example ) ? thank you

**Comment by codeslane** [comment]
@Nikeo Here the Screencast: http://screencast-o-matic.com/watch/cbfioQ6RWX
 
Long Tittle is causing issues.

**Comment by ghost** [comment]
OK Thank you

**Comment by codeslane** [comment]
I hope i helped you. 
Thanks
