### ISSUE TITLE
WP Hide & Security Enhancer Plugin Compatibility Issue. 

### ISSUE THREAD

**Issue by codeslane** [AlxMedia/hueman#453]
Sir @Nikeo, 
WP Hide & Security Enhancer Plugin is causing issues on when activating settings. 
Post Type and Set Featured Image dialogue box aren't showing even after the least activated settings. 

I deactivated the plugin and issue were solved. and after reactivating the plugin with same settings the Add New Post and All Posts Page isn't opening and showing a blank page on the site. (Wordpress CMS) 

In my another website the plugin with the different theme is working perfectly without causing any issues. (https://www.knowurcodes.com).
Because this plugin is already used by several thousands of users and is must be needed plugin for security reasons the issue should be solved.
Compatibility with this Hueman theme is required.  

Please make it compatible with WP Hide & Security Enhancer.

Thanks
-Vaibhav Pratap Singh

**Comment by ghost** [comment]
ok thanks for reporting the problem.

**Comment by codeslane** [comment]
@Nikeo its called white screen of death. 
Hope you got it
