### ISSUE TITLE
Customizer: blog controls visibility in the Front Page Content section

### ISSUE THREAD

**Issue by eri-trabiccolo** [AlxMedia/hueman#455]
- When displaying no page nor blog in home, the blog settings are visible,  do we really want this? :
 ![customizr_inconsistency](https://cloud.githubusercontent.com/assets/7689242/25304520/2adcc65e-2769-11e7-8705-9022de657952.png)
- Since the use of ubq do we still want the Jump to the blog design panel link? : ![customizr_inconsistency2](https://cloud.githubusercontent.com/assets/7689242/25304550/95f447f0-2769-11e7-8a9e-5f5d684ea502.png)

**Comment by ghost** [comment]
good catch. A dependency has to be added there yes I agree
