### ISSUE TITLE
Default order by param in post lists could be customizable. Now is it last update date ?

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#460]
> Please add an option to sort the posts by first publish date instead of last update date. Each time I perform a minor change of an older post it takes an undeserved 1st position in my posts list.

**Comment by ghost** [comment]
@eri-trabiccolo not sure about the default WP behaviour... Can you quickly check if the post list order change when a post is updated ?

**Comment by eri-trabiccolo** [comment]
https://codex.wordpress.org/Class_Reference/WP_Query#Order_.26_Orderby_Parameters
> orderby (string | array) - Sort retrieved posts by parameter. Defaults to 'date (post_date)'. One or more options can be passed.

So the publish date is the default one. (update date fied is 'modified' )

It works fine here, I cannot reproduce the issue
