### ISSUE TITLE
Missing <H1> on all woocommerce pages

### ISSUE THREAD

**Issue by SUGO-es** [AlxMedia/hueman#461]
Hi,

In the file int-plugins-compat.php, the hu_print_woocommerce_page_title ($ title) function forces all woocommerce pages to have a `<h2>` title, omitting any `<h1>` in all woocommerce.

          `<? Php else:?>
             <H2> <? Php woocommerce_page_title ()?> </ H2>
           <? Php endif?>`

I have changed this to:

           `<? Php else:?>
             <H1> <? Php woocommerce_page_title ()?> </ H1>
           <? Php endif?>`
And it already works correctly for me, I hope it helps.

Best regards and thanks for this great template.

**Comment by eri-trabiccolo** [comment]
Hi @xarkitu ,
thanks for reporting this and for providing the solution!

Best regards
