### ISSUE TITLE
Video widget not showing on Shop page

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#462]
> When adding the video widget on the website (on top of Primary sidebar) it works normally but when switching to shop page it only shows the youtube video link.
> 
> If I reorder the placement of the video widget for example to the secondary sidebar it works again.

**Comment by eri-trabiccolo** [comment]
Can't reproduce.
Maybe I don't get the issue:
![hueman-video](https://cloud.githubusercontent.com/assets/7689242/25429801/78735ad6-2a7a-11e7-90c9-beef4f314a31.png)

**Comment by ghost** [comment]
thx for the test. I'll give it a try on my side.
