### ISSUE TITLE
Sticky sidebar not well implemented on tablet devices

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#470]
http://wpconsultant.de/

> I have still the issue with the sticky sidebar on mobile. The sidebar is still sticky on mobile (tested on iPad 2 and iPad mini) even though the option is unchecked in customizer settings. So I suppose the wp_is_mobile() function doesn’t include these tablet sizes.
> 
> Could you please check it? I would really like to use the sticky sidebar but I had to turn it off also for desktop due to this issue.

**Comment by Nate82** [comment]
I think wp_is_mobile can be buggy and it's actually not recommended to use by a lot of people. I'd suggest https://github.com/serbanghita/Mobile-Detect if possible, I use Mobile-Detect with the Hueman theme and it works good.
