### ISSUE TITLE
Event Calendar : comments section is not visible in events

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#471]
>  I am stil strugling with this: I am using your theme together with the Event Calendar plugin https://wordpress.org/plugins/the-events-calendar/ and I have problem that I cant see the comments sections under events. Under regular posts or pages the comments section is visible but under event no. I did test: I switch off all plugins (except event calendar) than I switch to default theme Twenty sixteen or Twenty Eleven and the comments sections is vissible under events. So I supose there is something wrong with the theme.
> 
> Link to event where comments section is not visible
> http://blog.cabadaj.cz/zavod/rally-sweden/
> 
> Link to post – comments section is visible
> http://blog.cabadaj.cz/nepropasnete-jarni-vyprodej-na-xbox-live/
> 
> Link to page – comments section is visible
> http://blog.cabadaj.cz/vysledky-project-cars-gt3-cup-2017/
> 
> Can you please help me?
> Cabadaj

**Comment by ghost** [comment]
I'm fighting with this one.
@eri-trabiccolo if you have any clue ( next week no hurry)  I'll be glad to listen to them 👍

**Comment by eri-trabiccolo** [comment]
Will do, but last time I checked that with 2017 comment form didn't show on events.
