### ISSUE TITLE
Hueman + Hueman Addons : conflict with WP Touch Mobile ?

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#472]
https://wordpress.org/plugins/wptouch/

> 
After try everything i found the problem is that after last update have an incompatibility between Hueman Addons and WPtouch Mobile Plugin.

**Comment by ghost** [comment]
We'll talk about this tomorrow @eri-trabiccolo

**Comment by eri-trabiccolo** [comment]
I think I need more info on this.
What is the conflict? What doesn't work?

**Comment by eri-trabiccolo** [comment]
I see some problems in the customizer when hueman-addons is on and you switch to the mobile theme in the customizer (this switch is persistent).
One of them is related to this -> https://github.com/presscustomizr/hueman-pro-addons/issues/50
