### ISSUE TITLE
Bottom portion of Sidebar gets cut off in tablet view when content is short

### ISSUE THREAD

**Issue by denzelchia** [AlxMedia/hueman#476]
Hi,

Bottom portion of sidebar gets cut off in tablet view ( 480px to 960px  width ) when content is shorter than sidebar.

Please refer to the following forum post for steps to replicate this issue.
https://wordpress.org/support/topic/sidebar-truncated-in-tablet-view-at-short-pages/#post-9107274

Thank you

**Comment by eri-trabiccolo** [comment]
Another possible related topic:
https://wordpress.org/support/topic/sticky-sidebars-cutting-off-at-the-bottom/

**Comment by plimfec** [comment]
@eri-trabiccolo:
Thank you for labeling this as a bug. I think the initial 'enhancement' label is incorrect, because it really is a serious problem when parts of the content are being cut off by the design. I would even judge this as a showstopper in my own business and wouldn't go live this way.

Hopefully it is repaired soon, thanks for the efforts.

**Comment by ghost** [comment]
> https://wordpress.org/support/topic/cant-update-from-3-3-7-as-github-476-bug-still-cutting-content/#post-9265352
> 
> Wrong height applied to the sidebar.
> I think it depends on the fact the sidebar-content has display: none when collapsed (jQuery cannot retrieve its height)
> so here:
> https://github.com/presscustomizr/hueman/blob/v3.3.13/assets/front/css/dev-responsive.css#L96
> https://github.com/presscustomizr/hueman/blob/v3.3.13/assets/front/css/dev-responsive.css#L24
> 
> a display:block + visibility: hidden should be fine

**Comment by ghost** [comment]
https://wordpress.org/support/topic/2-cant-yet-update-from-3-3-7-as-github-476-bug-still-cutting-content/#post-9541453

**Comment by ghost** [comment]
The steps to provide the issue:
– Open the site and then narrow the screen below 960 px.
– When outlook changes to tablet view, open sidebar with toggle button.
– Scroll to the bottom of the page
– See right and left sidebar truncated
(Second link is showing scribd prentscreens of the issue.)
