### ISSUE TITLE
AMP plugin with Hueman theme

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#478]
> I have installed AMP and Accelerated Mobile Pages plugins on Hueman them which I have been using for a few years now, and the issue I found that when I go to appearance and then AMP to customise the AMP theme design it doesn't show up when using any other theme it seems to be working. Could you please provide me with a solution or fix this issue since I m sure a lot of people are using AMP plugin and if it doesn't allow you to customise it.

> - WordPress version 4.7.4 en GB
> - Hueman version 3.3.10
> - Accelerated Mobile page version 0.9.49 plugin
> - AMP version 0.4.2 plugin

https://wordpress.org/plugins/amp/

**Comment by ghost** [comment]
@eri-trabiccolo this plugin is used by a growing number of people. Can you take a look at the problem when you'll get the chance ?
Thanks !

**Comment by ghost** [comment]
The idea is to just quickly test the theme with https://wordpress.org/plugins/amp/ and we'll discuss what could be done to implement the best compatibility

**Comment by eri-trabiccolo** [comment]
I think we have an old issue open about this.
The amp plugin and the hueman addons didn't get along together (customizer), as far as I remember
Will look at it in a moment.

**Comment by eri-trabiccolo** [comment]
Ok after a rapid look at it I couldn't spot any particular issue, good!

Of course the whole AMP thing is about having specific AMP pages, meaning pages built with AMP elements. It's like having an additional theme.

**Comment by ghost** [comment]
OK.

**Comment by milindmore22** [comment]
Hello Team,
Can we please reopen this issue, I have created a PR to address basic menu toggle and search toggle issues
I will be happy to address any other issues
