### ISSUE TITLE
Yoast SEO Analysis Not Working

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#487]
> I've been running the Hueman free theme for a few months now and love it. However, my Yoast SEO (free) Analysis section is not working. It worked perfectly prior to updating to the Hueman theme. I've included a screenshot of the Analysis section. I have contacted Yoast about this issue, but unfortunately they will not help as I don't have the premium version.
> 
> http://imgur.com/a/q89fl
> 
> Thank you for your time and help!

> # THEME | VERSION : Hueman | v3.3.11
> # WP VERSION : 4.7.5
> # PERMALINK STRUCTURE : /%postname%/

**Comment by ghost** [comment]
Hi @eri-trabiccolo let's discuss this on Monday's coffee !

**Comment by eri-trabiccolo** [comment]
I don't seem to be able to reproduce this.
The analysis works here...
