### ISSUE TITLE
color of the menu items : possible cnadidate for options ?

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#489]
> Dear support staff,
> 
> I'm very pleased with the ease of use of your theme. It saved me a lot of time and work.
> 
> I noticed that the font color of the current menu/page item is set to white by default, and there is no option to change this. My top bar background color is set to white, so I added custom CSS to change the color of the current menu/page item to black. However, this is not very convenient for pages that may have set another top bar color, as my custom CSS code will simply override it, forcing me to use workarounds for every page that is in need of another font color.
> 
> Will you please consider adding the option to change the current menu/page item font color for all menus in a future update?
> Thank you kindly in advanced!
> 
> Sincerely,
> 
> Ferry
> Webmaster FadingMusic

**Comment by eri-trabiccolo** [comment]
if we could port wfc to skope...

**Comment by ghost** [comment]
Noooooooooooooooooooooooooooooooooooo
at least no the current version of wfc... :)
