### ISSUE TITLE
Issue in hu_get_raw_option, php warning

### ISSUE THREAD

**Issue by eri-trabiccolo** [AlxMedia/hueman#492]
https://secure.helpscout.net/conversation/370205302/27624/?folderId=607544

_Warning: array_key_exists() expects parameter 2 to be array, boolean given in [..]/hueman-pro/functions/init-functions.php on line 271_

Reported here as the user says it happens with hueman free too.

https://github.com/presscustomizr/hueman/blob/v3.3.11/functions/init-functions.php#L271
$alloptions might be not an array

Not sure in which conditions it happens.
Might be a conflicting plugin

**Comment by ghost** [comment]
ok thanks I'm on it
