### ISSUE TITLE
 Multisite : PHP Fatal error: Uncaught Error: Call to undefined function sanitize_hex_color_no_hash() in .../wp-content/themes/hueman/functions/init-functions.php:497

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#501]
> Hello,
> 
> we got this error on our WP 4.4.10 running Multisite mode:
> 
> PHP Fatal error: Uncaught Error: Call to undefined function sanitize_hex_color_no_hash() in .../wp-content/themes/hueman/functions/init-functions.php:497
> 
> I fixed that in code like this:
> 
> function hu_sanitize_hex_color( $color ) {
> 
> /// Addition 2017/06/01 by Foliovision
> 
> if( !function_exists('sanitize_hex_color_no_hash') ) return $color;
> 
> /// End of addition
> 
> if ( $unhashed = sanitize_hex_color_no_hash( $color ) )
> 
> return '#' . $unhashed;
> 
> return $color;
> 
> }
> 
> I'm not sure if the issue is related to the WP version or not, but please fix this on your end properly.
> 
> Thanks,

**Comment by eri-trabiccolo** [comment]
Another user reporting this:
https://secure.helpscout.net/conversation/401393141/30144/?folderId=607709

**Comment by eri-trabiccolo** [comment]
That function is available in WordPress outside the Customizer (moved in wp-includes/formatting.php) since WordPress 4.6 released in august last year.
