### ISSUE TITLE
POST http://wesbite.../?huajax=1 403 (Forbidden)

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#512]
![2017-06-19_10-50-41](https://user-images.githubusercontent.com/3038156/27277025-351e785a-54dd-11e7-890a-be14bcd45b9f.jpg)

**Comment by ghost** [comment]
http://alumnoaventajado.com/expertos-artes-marciales-scott-adkins/

**Comment by eri-trabiccolo** [comment]
https://www.universrumbacongolaise.com/
(WP rocket on)

http://alumnoaventajado.com/expertos-artes-marciales-scott-adkins/
(WP Fastest Cache on)

**Comment by eri-trabiccolo** [comment]
Mmm I was thinking it might depend on a nonce check failure (mismatch) when caching is on.
Consider that for that kind of front ajax actions we don't need to check it.

**Comment by ghost** [comment]
ah yes, that might be it actually

**Comment by caouic** [comment]
Hi,
I have still this error on hueman-pro version 1.0.18
https://www.lesgoodnews.fr/?huajax=1 403 forbiden
example:
[12/Sep/2017:08:53:46 +0200] "POST /?huajax=1 HTTP/1.1" 403 2 "https://www.lesgoodnews.fr/2016/05/05/la-garde-artistique-de-momartre/"
I'm using W3TC cache
Best regards,

**Comment by ghost** [comment]
@caouic thank you for reporting it.
