### ISSUE TITLE
H1 post / page headings should be slightlly taller than H2 headings inside the content.

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#515]
https://secure.helpscout.net/conversation/384537911/28826/?folderId=607546
Possible solution :
Changing 
```
.entry h2 {
    font-size: 2.125em;
    letter-spacing: -.7px;
}
```

To

```
.entry h2 {
    font-size: 2.125rem;
    letter-spacing: -.7px;
}
```

do the same ( em to rem in content ) for all other Hx

**Comment by eri-trabiccolo** [comment]
this makes them possibly not responsive (which is another concern of that user)

**Comment by ghost** [comment]
yep, hx headings need to be fittexted everywhere.

**Comment by ghost** [comment]
let's discuss it in a few minutes
