### ISSUE TITLE
__after_logo hook does not work anymore

### ISSUE THREAD

**Issue by cl1ent** [AlxMedia/hueman#518]
Hi,

after updating to 3.3.12 i'm experiencing issues with my site title. I was using the __after_logo hook found here: [https://presscustomizr.com/snippet/display-both-logo-and-title-in-header/](https://presscustomizr.com/snippet/display-both-logo-and-title-in-header/) which does not work anymore. I've of course now modified the hu_print_logo_or_title() function but having the hook would be the better option.

thanks

**Comment by ghost** [comment]
Hi @cl1ent This snippet was initially written for the customizr theme.
I don't think we implemented the `__after_logo` hook in the hueman theme.
It has been added with the name `__after_logo_or_site_title` the Hueman theme for v3.3.13.

**Comment by cl1ent** [comment]
hello @Nikeo 
thanks for your response. unfortunately using the `__after_logo_or_site_title` hook instead of the old one bricks the whole page. i am actually wondering why checking both options (show title and logo) in the customizer settings don't have the same effect.
i would really like to have my logo with corresponding site title back.

thanks

**Comment by cl1ent** [comment]
@Nikeo should i open a new issue for the question asked above?
