### ISSUE TITLE
 'load images on scroll' option makes images not visible on the site

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#524]
apparently since v3.3.13, at least 3 users have reported the problem.
Users says that clearing its cache plugin did not help. I don't have an url.

https://github.com/presscustomizr/hueman/compare/v3.3.12...v3.3.13

@eri-trabiccolo can you replicate the issue on your hand ?

**Comment by eri-trabiccolo** [comment]
nope, I cannot.
maybe a website where this happens could help.

**Comment by ghost** [comment]
https://www.neutrondev.com/

**Comment by eri-trabiccolo** [comment]
Ok,
now the user has the theme's load images on scroll disabled.
Also the posts images have a lot of additional attributes not coming from the theme, so a conflict with a plugin might be the reason.
