### ISSUE TITLE
Featured image height in recomended posts

### ISSUE THREAD

**Issue by pavelsterba** [AlxMedia/hueman#525]
Since (most likely) _v3.3.14_ there is "problem" with featured image height in recomended post on homepage. Before this release, height was fixed, independent on actual image height (only part of image was displayed). Since that, whole image is displayed, which can break homepage or make page too long without reason... When you check developer console, you will see:

`attachment- size- wp-post-image`

Isn't there something missing after `attachment-` and `size-`? In previous version, there was:

`attachment-thumb-large size-thumb-large wp-post-image`

Can this cause the problem?

**Comment by pavelsterba** [comment]
Can https://github.com/presscustomizr/hueman/issues/350 be related to this?

> fixed : on the blog page, the ( optional ) featured posts thumbnail size was not large enough when using a 1 or 2 columns layout. 'thumb-large' size is now only used for 3 columns layout. Fixes #350

**Comment by ghost** [comment]
Thank you for reporting this.
which height would be acceptable for you ?
Would it be interesting for you to be able to set the height of the featured post from the customizer ?

Thanks for your feedback

**Comment by caouic** [comment]
Hi,
I've the same problem for my website.
[http://www.lesgoodnews.fr](url)
The .flexslider .slides img  height is too high
400px will be ok
Best regards,

**Comment by ghost** [comment]
A fix is on the way.
