### ISSUE TITLE
WP Hide & Security Plugin Issue

### ISSUE THREAD

**Issue by codeslane** [AlxMedia/hueman#526]
Neko, 
Hueman Demo is creating an issue with WP Hide & Security Plugin.

Menus aren't opening and aren't clickable. Menus aren't responding when clicking.
When I turned off the Script Version from Plugin. Menus again started working but still lagging on menu scrolling. 

Please Fix this issue. 

Thanks.

**Comment by ghost** [comment]
Hi, thank you for reporting.
Could you provide the url of the plugin on wp.org ? I want to be sure to test the same as you.
Thanks !

**Comment by codeslane** [comment]
Here's the plugin url.

https://wordpress.org/plugins/wp-hide-security-enhancer/ 

This plugin isn't fully compatible with hueman. 

Some options break the theme functionality. 
Also please note this plugin only effect htaccess file and doesn't change any theme settings.
