### ISSUE TITLE
Slider Header Issue

### ISSUE THREAD

**Issue by codeslane** [AlxMedia/hueman#527]
Slider Headers are hiding under top bar header in Mobile View.

Please Fix.

**Comment by ghost** [comment]
Hi, thanks for reporting. Could you provide a screenshot and / or and url ?
Thank you @codeslane

**Comment by codeslane** [comment]
https://www.codeslane.com 

The problem is in mobile view only.

**Comment by ghost** [comment]
OK thank you.
This will be addressed in v3.3.19

![2017-07-07_09-57-32](https://user-images.githubusercontent.com/3038156/27948695-0f3a0f2e-62fb-11e7-8684-021d214535fe.jpg)
