### ISSUE TITLE
More specificity when targeting the sidebars: use elements ids

### ISSUE THREAD

**Issue by eri-trabiccolo** [AlxMedia/hueman#529]
https://secure.helpscout.net/conversation/389005905/29167/?folderId=607709

For some reason in the page/post text of the user's site span elements have a progressive CSS class sN (N=1 ... )

Since hueman uses s1 and s2 classes to target the sidebars basically all the page/post content is hidden, plus the sidebars do not un-collapse in tablet viewports!

**Comment by ghost** [comment]
ok.
Can you replicate ?
What is the plugin in conflict ?

**Comment by eri-trabiccolo** [comment]
No info about the plugin which creates that structure. I think is a plugin but might even not be so.
Yes I can reproduce the issue when I put an element with s1 class in the page/post text.

**Comment by ghost** [comment]
ok thanks
