### ISSUE TITLE
Error Message when using Jetpack : Call to undefined function ot_register_meta_box()

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#541]
> I have tested this on a fresh WordPress install which included Twenty-Seventeen as the default theme. With that theme installed, then installing and connecting Jetpack to WordPress.com, I can view the plugins on the site from my WordPress.com dashboard. However, when I switch the theme to Hueman Free, I get an error on WordPress.com that it could not fetch plugins from my site. WordPress/Jetpack support showed me how to generate an error log file, and I will include the text from it below.
> 
> I think your theme is great, and if you can get this working, it would be perfect!
> 
> Thanks!
> 
> Wayne Cochran

debug.log

[10-Jul-2017 11:45:20 UTC] WP_Community_Events::maybe_log_events_response: Valid response received. Details: {"api_url":"https:\/\/api.wordpress.org\/events\/1.0\/","request_args":{"body":{"number":5,"ip":"205.189.255.0","locale":"en_US","timezone":"America\/New_York"}},"response_code":200,"response_body":{"location":{"ip":"205.189.255.0"},"events":"5 events trimmed."}}
[10-Jul-2017 11:45:37 UTC] Array
(
[akismet_debug] => Array
(
[akismet_url] => https://ad3767ea151e.rest.akismet.com/1.1/verify-key
[http_args] => Array
(
[body] => key=ad3767ea151e&blog=https%3A%2F%2Fwaynecochran.net
[headers] => Array
(
[Content-Type] => application/x-www-form-urlencoded; charset=UTF-8
[Host] => ad3767ea151e.rest.akismet.com
[User-Agent] => WordPress/4.8 | Akismet/3.3.2
)

[httpversion] => 1.0
[timeout] => 15
)

[response] => Array
(
[headers] => Requests_Utility_CaseInsensitiveDictionary Object
(
[data:protected] => Array
(
[server] => nginx
[date] => Mon, 10 Jul 2017 11:45:37 GMT
[content-type] => text/plain; charset=utf-8
[content-length] => 5
)

)

[body] => valid
[response] => Array
(
[code] => 200
[message] => OK
)

[cookies] => Array
(
)

[filename] =>
[http_response] => WP_HTTP_Requests_Response Object
(
[response:protected] => Requests_Response Object
(
[body] => valid
[raw] => HTTP/1.1 200 OK
Server: nginx
Date: Mon, 10 Jul 2017 11:45:37 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 5
Connection: close

valid
[headers] => Requests_Response_Headers Object
(
[data:protected] => Array
(
[server] => Array
(
[0] => nginx
)

[date] => Array
(
[0] => Mon, 10 Jul 2017 11:45:37 GMT
)

[content-type] => Array
(
[0] => text/plain; charset=utf-8
)

[content-length] => Array
(
[0] => 5
)

)

)

[status_code] => 200
[protocol_version] => 1.1
[success] => 1
[redirects] => 0
[url] => https://ad3767ea151e.rest.akismet.com/1.1/verify-key
[history] => Array
(
)

[cookies] => Requests_Cookie_Jar Object
(
[cookies:protected] => Array
(
)

)

)

[filename:protected] =>
[data] =>
[headers] =>
[status] =>
)

)

)

)

[10-Jul-2017 11:45:37 UTC] Array
(
[akismet_debug] => Array
(
[akismet_url] => https://ad3767ea151e.rest.akismet.com/1.1/verify-key
[http_args] => Array
(
[body] => key=ad3767ea151e&blog=https%3A%2F%2Fwaynecochran.net
[headers] => Array
(
[Content-Type] => application/x-www-form-urlencoded; charset=UTF-8
[Host] => ad3767ea151e.rest.akismet.com
[User-Agent] => WordPress/4.8 | Akismet/3.3.2
)

[httpversion] => 1.0
[timeout] => 15
)

[response] => Array
(
[headers] => Requests_Utility_CaseInsensitiveDictionary Object
(
[data:protected] => Array
(
[server] => nginx
[date] => Mon, 10 Jul 2017 11:45:37 GMT
[content-type] => text/plain; charset=utf-8
[content-length] => 5
)

)

[body] => valid
[response] => Array
(
[code] => 200
[message] => OK
)

[cookies] => Array
(
)

[filename] =>
[http_response] => WP_HTTP_Requests_Response Object
(
[response:protected] => Requests_Response Object
(
[body] => valid
[raw] => HTTP/1.1 200 OK
Server: nginx
Date: Mon, 10 Jul 2017 11:45:37 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 5
Connection: close

valid
[headers] => Requests_Response_Headers Object
(
[data:protected] => Array
(
[server] => Array
(
[0] => nginx
)

[date] => Array
(
[0] => Mon, 10 Jul 2017 11:45:37 GMT
)

[content-type] => Array
(
[0] => text/plain; charset=utf-8
)

[content-length] => Array
(
[0] => 5
)

)

)

[status_code] => 200
[protocol_version] => 1.1
[success] => 1
[redirects] => 0
[url] => https://ad3767ea151e.rest.akismet.com/1.1/verify-key
[history] => Array
(
)

[cookies] => Requests_Cookie_Jar Object
(
[cookies:protected] => Array
(
)

)

)

[filename:protected] =>
[data] =>
[headers] =>
[status] =>
)

)

)

)

[10-Jul-2017 11:45:37 UTC] Array
(
[akismet_debug] => Array
(
[akismet_url] => https://ad3767ea151e.rest.akismet.com/1.1/get-stats
[http_args] => Array
(
[body] => blog=https%3A%2F%2Fwaynecochran.net&key=ad3767ea151e&from=6-months
[headers] => Array
(
[Content-Type] => application/x-www-form-urlencoded; charset=UTF-8
[Host] => ad3767ea151e.rest.akismet.com
[User-Agent] => WordPress/4.8 | Akismet/3.3.2
)

[httpversion] => 1.0
[timeout] => 15
)

[response] => Array
(
[headers] => Requests_Utility_CaseInsensitiveDictionary Object
(
[data:protected] => Array
(
[server] => nginx
[date] => Mon, 10 Jul 2017 11:45:37 GMT
[content-type] => text/plain; charset=utf-8
[vary] => Accept-Encoding
[content-encoding] => gzip
)

)

[body] => {"spam":1216,"ham":11,"missed_spam":2,"false_positives":0,"accuracy":"99.83","breakdown":{"2017-01":{"spam":"149","ham":"0","missed_spam":"2","false_positives":"0","da":"2017-01-01"},"2017-02":{"spam":"2","ham":"0","missed_spam":"0","false_positives":"0","da":"2017-02-01"},"2017-03":{"spam":"843","ham":"0","missed_spam":"0","false_positives":"0","da":"2017-03-01"},"2017-04":{"spam":"199","ham":"0","missed_spam":"0","false_positives":"0","da":"2017-04-01"},"2017-05":{"spam":"2","ham":"1","missed_spam":"0","false_positives":"0","da":"2017-05-01"},"2017-06":{"spam":"20","ham":"10","missed_spam":"0","false_positives":"0","da":"2017-06-01"},"2017-07":{"spam":"1","ham":"0","missed_spam":"0","false_positives":"0","da":"2017-07-01"}},"time_saved":36990}
[response] => Array
(
[code] => 200
[message] => OK
)

[cookies] => Array
(
)

[filename] =>
[http_response] => WP_HTTP_Requests_Response Object
(
[response:protected] => Requests_Response Object
(
[body] => {"spam":1216,"ham":11,"missed_spam":2,"false_positives":0,"accuracy":"99.83","breakdown":{"2017-01":{"spam":"149","ham":"0","missed_spam":"2","false_positives":"0","da":"2017-01-01"},"2017-02":{"spam":"2","ham":"0","missed_spam":"0","false_positives":"0","da":"2017-02-01"},"2017-03":{"spam":"843","ham":"0","missed_spam":"0","false_positives":"0","da":"2017-03-01"},"2017-04":{"spam":"199","ham":"0","missed_spam":"0","false_positives":"0","da":"2017-04-01"},"2017-05":{"spam":"2","ham":"1","missed_spam":"0","false_positives":"0","da":"2017-05-01"},"2017-06":{"spam":"20","ham":"10","missed_spam":"0","false_positives":"0","da":"2017-06-01"},"2017-07":{"spam":"1","ham":"0","missed_spam":"0","false_positives":"0","da":"2017-07-01"}},"time_saved":36990}
[raw] => HTTP/1.1 200 OK
Server: nginx
Date: Mon, 10 Jul 2017 11:45:37 GMT
Content-Type: text/plain; charset=utf-8
Transfer-Encoding: chunked
Connection: close
Vary: Accept-Encoding
Content-Encoding: gzip

{"spam":1216,"ham":11,"missed_spam":2,"false_positives":0,"accuracy":"99.83","breakdown":{"2017-01":{"spam":"149","ham":"0","missed_spam":"2","false_positives":"0","da":"2017-01-01"},"2017-02":{"spam":"2","ham":"0","missed_spam":"0","false_positives":"0","da":"2017-02-01"},"2017-03":{"spam":"843","ham":"0","missed_spam":"0","false_positives":"0","da":"2017-03-01"},"2017-04":{"spam":"199","ham":"0","missed_spam":"0","false_positives":"0","da":"2017-04-01"},"2017-05":{"spam":"2","ham":"1","missed_spam":"0","false_positives":"0","da":"2017-05-01"},"2017-06":{"spam":"20","ham":"10","missed_spam":"0","false_positives":"0","da":"2017-06-01"},"2017-07":{"spam":"1","ham":"0","missed_spam":"0","false_positives":"0","da":"2017-07-01"}},"time_saved":36990}
[headers] => Requests_Response_Headers Object
(
[data:protected] => Array
(
[server] => Array
(
[0] => nginx
)

[date] => Array
(
[0] => Mon, 10 Jul 2017 11:45:37 GMT
)

[content-type] => Array
(
[0] => text/plain; charset=utf-8
)

[vary] => Array
(
[0] => Accept-Encoding
)

[content-encoding] => Array
(
[0] => gzip
)

)

)

[status_code] => 200
[protocol_version] => 1.1
[success] => 1
[redirects] => 0
[url] => https://ad3767ea151e.rest.akismet.com/1.1/get-stats
[history] => Array
(
)

[cookies] => Requests_Cookie_Jar Object
(
[cookies:protected] => Array
(
)

)

)

[filename:protected] =>
[data] =>
[headers] =>
[status] =>
)

)

)

)

[10-Jul-2017 11:45:38 UTC] Array
(
[akismet_debug] => Array
(
[akismet_url] => https://ad3767ea151e.rest.akismet.com/1.1/get-stats
[http_args] => Array
(
[body] => blog=https%3A%2F%2Fwaynecochran.net&key=ad3767ea151e&from=all
[headers] => Array
(
[Content-Type] => application/x-www-form-urlencoded; charset=UTF-8
[Host] => ad3767ea151e.rest.akismet.com
[User-Agent] => WordPress/4.8 | Akismet/3.3.2
)

[httpversion] => 1.0
[timeout] => 15
)

[response] => Array
(
[headers] => Requests_Utility_CaseInsensitiveDictionary Object
(
[data:protected] => Array
(
[server] => nginx
[date] => Mon, 10 Jul 2017 11:45:38 GMT
[content-type] => text/plain; charset=utf-8
[vary] => Accept-Encoding
[content-encoding] => gzip
)

)

[body] => {"spam":20923,"ham":725,"missed_spam":46,"false_positives":0,"accuracy":"99.78","breakdown":{"2011":{"spam":0,"ham":0,"missed_spam":0,"false_positives":0,"da":"2011-01-01"},"2012":{"spam":44,"ham":2,"missed_spam":0,"false_positives":0,"da":"2012-01-01"},"2013":{"spam":4095,"ham":24,"missed_spam":3,"false_positives":0,"da":"2013-01-01"},"2014":{"spam":4248,"ham":674,"missed_spam":35,"false_positives":0,"da":"2014-01-01"},"2015":{"spam":3106,"ham":1,"missed_spam":2,"false_positives":0,"da":"2015-01-01"},"2016":{"spam":8214,"ham":13,"missed_spam":4,"false_positives":0,"da":"2016-01-01"},"2017":{"spam":1216,"ham":11,"missed_spam":2,"false_positives":0,"da":"2017-01-01"}},"time_saved":156365}
[response] => Array
(
[code] => 200
[message] => OK
)

[cookies] => Array
(
)

[filename] =>
[http_response] => WP_HTTP_Requests_Response Object
(
[response:protected] => Requests_Response Object
(
[body] => {"spam":20923,"ham":725,"missed_spam":46,"false_positives":0,"accuracy":"99.78","breakdown":{"2011":{"spam":0,"ham":0,"missed_spam":0,"false_positives":0,"da":"2011-01-01"},"2012":{"spam":44,"ham":2,"missed_spam":0,"false_positives":0,"da":"2012-01-01"},"2013":{"spam":4095,"ham":24,"missed_spam":3,"false_positives":0,"da":"2013-01-01"},"2014":{"spam":4248,"ham":674,"missed_spam":35,"false_positives":0,"da":"2014-01-01"},"2015":{"spam":3106,"ham":1,"missed_spam":2,"false_positives":0,"da":"2015-01-01"},"2016":{"spam":8214,"ham":13,"missed_spam":4,"false_positives":0,"da":"2016-01-01"},"2017":{"spam":1216,"ham":11,"missed_spam":2,"false_positives":0,"da":"2017-01-01"}},"time_saved":156365}
[raw] => HTTP/1.1 200 OK
Server: nginx
Date: Mon, 10 Jul 2017 11:45:38 GMT
Content-Type: text/plain; charset=utf-8
Transfer-Encoding: chunked
Connection: close
Vary: Accept-Encoding
Content-Encoding: gzip

{"spam":20923,"ham":725,"missed_spam":46,"false_positives":0,"accuracy":"99.78","breakdown":{"2011":{"spam":0,"ham":0,"missed_spam":0,"false_positives":0,"da":"2011-01-01"},"2012":{"spam":44,"ham":2,"missed_spam":0,"false_positives":0,"da":"2012-01-01"},"2013":{"spam":4095,"ham":24,"missed_spam":3,"false_positives":0,"da":"2013-01-01"},"2014":{"spam":4248,"ham":674,"missed_spam":35,"false_positives":0,"da":"2014-01-01"},"2015":{"spam":3106,"ham":1,"missed_spam":2,"false_positives":0,"da":"2015-01-01"},"2016":{"spam":8214,"ham":13,"missed_spam":4,"false_positives":0,"da":"2016-01-01"},"2017":{"spam":1216,"ham":11,"missed_spam":2,"false_positives":0,"da":"2017-01-01"}},"time_saved":156365}
[headers] => Requests_Response_Headers Object
(
[data:protected] => Array
(
[server] => Array
(
[0] => nginx
)

[date] => Array
(
[0] => Mon, 10 Jul 2017 11:45:38 GMT
)

[content-type] => Array
(
[0] => text/plain; charset=utf-8
)

[vary] => Array
(
[0] => Accept-Encoding
)

[content-encoding] => Array
(
[0] => gzip
)

)

)

[status_code] => 200
[protocol_version] => 1.1
[success] => 1
[redirects] => 0
[url] => https://ad3767ea151e.rest.akismet.com/1.1/get-stats
[history] => Array
(
)

[cookies] => Requests_Cookie_Jar Object
(
[cookies:protected] => Array
(
)

)

)

[filename:protected] =>
[data] =>
[headers] =>
[status] =>
)

)

)

)

[10-Jul-2017 11:46:13 UTC] PHP Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'ot_add_xml_to_upload_filetypes' not found or invalid function name in /home3/gwcochran/public_html/wp-includes/class-wp-hook.php on line 298
[10-Jul-2017 11:46:13 UTC] PHP Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'ot_save_settings' not found or invalid function name in /home3/gwcochran/public_html/wp-includes/class-wp-hook.php on line 298
[10-Jul-2017 11:46:13 UTC] PHP Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'ot_modify_layouts' not found or invalid function name in /home3/gwcochran/public_html/wp-includes/class-wp-hook.php on line 298
[10-Jul-2017 11:46:13 UTC] PHP Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'ot_create_media_post' not found or invalid function name in /home3/gwcochran/public_html/wp-includes/class-wp-hook.php on line 298
[10-Jul-2017 11:46:13 UTC] PHP Fatal error: Call to undefined function ot_register_meta_box() in /home3/gwcochran/public_html/wp-content/themes/hueman/functions/init-admin.php on line 434
[10-Jul-2017 11:46:38 UTC] PHP Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'ot_add_xml_to_upload_filetypes' not found or invalid function name in /home3/gwcochran/public_html/wp-includes/class-wp-hook.php on line 298
[10-Jul-2017 11:46:38 UTC] PHP Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'ot_save_settings' not found or invalid function name in /home3/gwcochran/public_html/wp-includes/class-wp-hook.php on line 298
[10-Jul-2017 11:46:38 UTC] PHP Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'ot_modify_layouts' not found or invalid function name in /home3/gwcochran/public_html/wp-includes/class-wp-hook.php on line 298
[10-Jul-2017 11:46:38 UTC] PHP Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'ot_create_media_post' not found or invalid function name in /home3/gwcochran/public_html/wp-includes/class-wp-hook.php on line 298
[10-Jul-2017 11:46:38 UTC] PHP Fatal error: Call to undefined function ot_register_meta_box() in /home3/gwcochran/public_html/wp-content/themes/hueman/functions/init-admin.php on line 434

**Comment by eri-trabiccolo** [comment]
> I can view the plugins on the site from my WordPress.com dashboard.

so ... institutional account?! :P

**Comment by ghost** [comment]
In the error log, there's PHP Fatal error: Call to undefined function ot_register_meta_box()  in /home3/gwcochran/public_html/wp-content/themes/hueman/functions/init-admin.php on line 434

**Comment by eri-trabiccolo** [comment]
From my tests:
when on that wp.com platform admin_init is fire but is_admin() is false.
Mah
