### ISSUE TITLE
<!--nextpage-->  Doesn't apply in Pages.

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#550]
> Hi Support
> 
> I have around 400 Pages where some have up to 20 'subpages'. It works in Posts but the function
> 
> 
> Doesn't apply in Pages.
> 
> I was considering buying the Theme. However I need to know how to fix that before buy.
> 
> Another minor thing in Customizr it's possible to edit a single post or page straight from the Front End when logged in to the Backend. It doesn't seem to be possible in Humaen Theme ?
> 
> Well. Anyway it's a great Theme and I consider to buy it. However you have an offer ending today on the Theme.
> 
> Best Regards
> 
> Claus Gamborg
> 
> Clean Chess
> 
> https://www.cleanchess.com

**Comment by ghost** [comment]
@eri-trabiccolo no hurry we'll tak about it during our point tomorrow.
cheers

**Comment by eri-trabiccolo** [comment]
Not so much to talk though :)
single:
https://github.com/presscustomizr/hueman/blob/dev/tmpl/single-tmpl.php#L16
page:
https://github.com/presscustomizr/hueman/blob/dev/tmpl/page-tmpl.php#L9
