### ISSUE TITLE
new option display the full posts content on home, and the content of those posts should be formatted the same way it is when displayed as singular post

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#555]
> The text formatting on the post on the home page is broken. It's not formatting the the content correctly and the text in a new paragraph appears on the next line rather than with a line spaced between paragraphs. I have clicked and clicked and clicked and CANNOT get this to function correctly. I've set it so that full text content should display for the posts, but it's messing up the new paragraphs. If I go to the individual post, then sanity returns and it displays correctly, no featured image and properly formatted paragraphs.

This is what it looks like on the home page:-
![de228463afcf2eec67eb76c8faf15f9c](https://user-images.githubusercontent.com/3038156/29145196-62684bfe-7d5c-11e7-983a-0301c6bf47b9.png)

And this is what it looks like on the individual post:-
![be2aecd19c9ddf71fcff1984576b39c2](https://user-images.githubusercontent.com/3038156/29145203-69a7b486-7d5c-11e7-8ede-8f3699f7f932.png)

**Comment by ghost** [comment]
https://secure.helpscout.net/conversation/408734594/30712/?folderId=607547

**Comment by eri-trabiccolo** [comment]
requested again, same user:
https://secure.helpscout.net/conversation/485549330/35445?folderId=607709
