### ISSUE TITLE
site title issue in multisite installs

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#561]
> The other issue is simply that once I decided to use a private multisite for each of my domains, your theme had some off behaviors. I imagine you can fix them pretty easily though. It's hard to explain, but I'll try. So, my main site was rswfire.blog in the multisite setup I did. I have nine other domains all starting with rswfire. Your theme was setting the meta title to rswfire.blog on -every- site. It also did this to the admin bar at the top (when you're logged in). On a multisite, there's a dropdown of sites and your theme showed all ten as rswfire.blog again.

**Comment by ghost** [comment]
https://secure.helpscout.net/conversation/414254001/31111/?folderId=607546

**Comment by eri-trabiccolo** [comment]
should be this?
https://github.com/presscustomizr/hueman-pro-addons/issues/97

**Comment by ghost** [comment]
https://secure.helpscout.net/conversation/501770035/36376?folderId=607544

**Comment by ghost** [comment]
fixed in presscustomizr/skope#8
