### ISSUE TITLE
'hu' functions don't work in child themes

### ISSUE THREAD

**Issue by a8bit** [AlxMedia/hueman#564]
hu_get_content and hu_get_template_part don't include files from tmpl/ or parts/ in the parent theme or modified versions in the child theme. 

hu_is_authorized_tmpl is stopping any files apart from the standard six from being included. 

This breaks all the theming. I can create custom post_types but I cannot theme them using the human theme parts. 

Some parts of the theme are looking for specific post_types rather than excluding the ones it doesn't want so styles are not applied uniformly either.

**Comment by answerquest** [comment]
I found a fix, but had to make it in the parent theme and so will have to edit the parent theme after every update. Hence, requesting the developers to do this small change:

Please make the function `hu_is_authorized_tmpl` [(functions/init-front.php:47)](https://github.com/presscustomizr/hueman/blob/dev/functions/init-front.php#L47) as **pluggable**, as defined in [the documentation](http://docs.presscustomizr.com/article/239-using-a-child-theme-with-hueman).

```
if( ! function_exists('hu_is_authorized_tmpl') ) {
  function hu_is_authorized_tmpl( $tmpl ) {
    $ct_map = apply_filters(
        'hu_content_map',
        array( 'tmpl/index-tmpl', 'tmpl/archive-tmpl', 'tmpl/page-tmpl', 'tmpl/single-tmpl', 'tmpl/search-tmpl', 'tmpl/404-tmpl' )
    );
    //Are we good after filtering ?
    if ( ! is_array( $ct_map ) || ! is_string( $tmpl ) )
      return;
    return in_array( $tmpl, $ct_map );
}
}
```

A detailed log of my use case is in the [wordpress support forum in this topic](https://wordpress.org/support/topic/custom-single-post-template-for-specific-category-2/#post-9822474).

This will enable child theme users to re-define the `hu_is_authorized_tmpl` function in their `functions.php` and hence expand the allowed list to include templates created for custom post types etc.

I also found through this that whlle the [the documentation](http://docs.presscustomizr.com/article/239-using-a-child-theme-with-hueman) says that the hueman child theme will first look in child theme folder for the file and then in parent theme folder with the only exception being functions.php, this wasn't the case for `functions/init-front.php`. I had put an edited version in my child theme but hueman directly went to the parent theme. My site's error log proved this:

`[30-Dec-2017 16:48:16 UTC] PHP Fatal error:  Cannot redeclare hu_is_authorized_tmpl() (previously declared in /..path../wp-content/themes/hueman-tropicsu/functions.php:11) in /..path../wp-content/themes/hueman/functions/init-front.php on line 56`

**Comment by elle8che** [comment]
Amazing that this issue still persists in 2023. Do I have to do this duct tape method just for this theme to work? I can't fathom considering paying for the pro version if the free version causes this much strife. I have spent too much valuable time and effort just to find the source of this issue during my development.

**Comment by Arskrigitsioniets** [comment]
Hello from 2023. I hope this function will be pluggable in the following update.
