### ISSUE TITLE
Request: More custom Google fonts

### ISSUE THREAD

**Issue by Tarun80** [AlxMedia/hueman#565]
For example, can we have the regular Roboto added?
https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i

**Comment by codeslane** [comment]
@Tarun80 you can use google fonts plugins. 

It will enhance the typography on your customisation. 

Thanks

**Comment by Tarun80** [comment]
Is that in the WordPress site or a custom plugin as part of Hueman? I put in the request because fewer plugins are better and I'd prefer to avoid using too many plugins.

**Comment by Tarun80** [comment]
@Nikeo Is there any way to add what I mentioned in my first post? Trying to do so as a child theme doesn't work.

**Comment by Tarun80** [comment]
@Nikeo - any word on this? It can't be added via child themes, and has to be added by editing a php file which gets replaced every update.
