### ISSUE TITLE
CSS conflict with Contact Form 7's form validation message

### ISSUE THREAD

**Issue by denzelchia** [AlxMedia/hueman#570]
Hi,

Please refer to this thread.
https://wordpress.org/support/topic/cf7-validation-setting-static-not-working/

Theme is adding background color and floating the contact form's validation message.
I had provided some css code to user to fix this issue.

Thank you

**Comment by ghost** [comment]
thanks for reporting the problem @denzelchia

**Comment by denzelchia** [comment]
You are welcome!
Thank you.
