### ISSUE TITLE
Add new option to control the visibility of post metas : date, author, taxonomies

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#573]
> Can't find a Check box to sellect wther I want to show auther and/or date of a post....

https://secure.helpscout.net/conversation/444091716/32994/?folderId=610151

**Comment by ghost** [comment]
Reported again by several users recently.

Example :
https://secure.helpscout.net/conversation/479221489/35130/
> Also is there a way to remove the categories of a post from the front page?

**Comment by eri-trabiccolo** [comment]
requested also:
https://secure.helpscout.net/conversation/534788879/38527?folderId=607709
https://secure.helpscout.net/conversation/526417869/38007?folderId=607541

and recently:
https://wordpress.org/support/topic/remove-post-date-on-home-page/
