### ISSUE TITLE
Child theme style.css should be loaded after the dynamic style

### ISSUE THREAD

**Issue by eri-trabiccolo** [AlxMedia/hueman#577]
While at the moment it is loaded after the main theme style but before the dynamic style.
This means that, given equal selectors weight, a dyn style rule will win.

Not sure this is the desired behavior.

In Customizr the child-theme style.css is loaded after the custom-skin.

reported here:
https://wordpress.org/support/topic/customise-hyperlink-font-colour/

**Comment by ghost** [comment]
Thanks for reporting this.  Yep that's right.
I'm fixing it.

The new order will be 

1. main
2. dynamic
3. wp-custom-css ( if any )

and if child theme

1. main
2. dynamic
3. child theme
4. wp-custom-css ( if any )
