### ISSUE TITLE
SHARRRE with Google+ cannot be used

### ISSUE THREAD

**Issue by studioart** [AlxMedia/hueman#58]
Hi,

I cannot use the SHARRRE bar together with the G+ button.

Warning: curl_setopt_array(): CURLOPT_FOLLOWLOCATION cannot be activated when an open_basedir is set in ....... /js/sharrre.php on line 56
{"url":"http://sharrre.com/","count":0}

My hoster said, that oben_basedir has been set for security reasons and they won't change that.

Isn't there another solution to implement the G+ button for using within HUEMAN's social sharing bar for all those users, who have the same server settings?
Thanks.

**Comment by AlxMedia** [comment]
Currently sharrre needs it to work, so all I can suggest is to disable it and use a plugin instead. Sorry for a very late reply.
