### ISSUE TITLE
( Hueman Pro ) Font Customizer Preview is not working properly

### ISSUE THREAD

**Issue by denzelchia** [AlxMedia/hueman#582]
Hi,

I am using Hueman Pro theme, no plugin activated, and on Firefox browser.

In Font Customizer -> Posts / Pages -> H2 headings

After clicking on Save and Publish button, The selected font size and font color does not apply in preview. It's being reverted back to default.

However, on front-end, after clicking on browser refresh, the changes are shown on front end.
This shows that issue is only in Customizer Preview.

Please see my screen-cast which explains the above mentioned issue.
http://screencast-o-matic.com/watch/cb6FetI7qb

I did not test other settings.

This issue is reported on the following helpscout thread.
https://secure.helpscout.net/conversation/450972650/33472?folderId=607541#thread-1221638098

Have a nice day,

Best regards,
Denzel

**Comment by denzelchia** [comment]
Hi @Nikeo 

Please reply if you had seen this issue report.

Here is another user with the same problem.
https://secure.helpscout.net/conversation/450807709/33459/?folderId=607546#thread-1223077764

Thank you

**Comment by ghost** [comment]
Yes got it Denzel. Thank you for reporting it.

**Comment by ghost** [comment]
Moved to WFC https://github.com/presscustomizr/wordpress-font-customizer/issues/76
