### ISSUE TITLE
Event Calendar not working on mobile

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#587]
> Dear Sir,
> 
> I have the latest version of WordPress, the latest (free) version of Hueman Theme and the latest (free) version of the Events Calendar.
> 
> On desktop everything is working fine, but on mobile (iphone 6s and iphone 4) the Single Event is not displaying (only the title and the featured image, no text).
> 
> The page with all Events displays nothing on mobile. The Events Calendar says that it is a problem with the Theme.
> 
> Any ideas?
> 
> The website: www.tenerifevakantie.com
> 
> The events page: www.tenerifevakantie.com/events/
> 
> Hope you can help me.
> 
> Regards,

**Comment by eri-trabiccolo** [comment]
I actually went from desktop on that events page and it didn't display. The I hard-refreshed the page and it displayed.
I went from my android and worked fine. Not sure is a theme related bug.
If it is, it might be something related to the server configuration

**Comment by ghost** [comment]
Yep, you are right. The problem is solved also on user side.

> Hi Nicolas,
> 
> For the moment the problem is solved, it seems a cache problem by the hosting company Flywheel.
> 
> Thanks and best regards,
> Guy Hacha
