### ISSUE TITLE
Problem with plugin Jetpack

### ISSUE THREAD

**Issue by paconarud** [AlxMedia/hueman#593]
Good afternoon and first of all thanks for the work done in the theme. Since the last update of wordpress 4.8.3 I can not customize the theme. I currently have a child theme and updated to the latest version 3.3.22. When I try to personalize the theme I jump the screen of gavatar or jetpack. I tried disabling the plugin and it did not work either. How could I solve it? How could I access the personalization panel in another way?
It turns out that the problem for not being able to customize the theme is the compatibility with the latest jetpack updates, has it happened to anyone else? Is there any kind of solution ?, every time I have to customize I have to disable the plugin and then reactivate it again. I need your help. Thank you.

this is the information about my instalation of wordpress

# SITE_URL:               https://www.atme.es
# HOME_URL:               https://www.atme.es
# IS MULTISITE :          No

# THEME | VERSION :       Hueman | v3.3.22
# WP VERSION :            4.8.3
# PERMALINK STRUCTURE :   /%postname%/
# 44 ACTIVE PLUGINS :
                          - Akismet Anti-Spam (version 4.0.1)
                          - Bulk Delete (version 5.5.7)
                          - Caldera Forms (version 1.5.7.1)
                          - Childify Me (version 1.1.1)
                          - Cookie Ley Española (version 1.4)
                          - Download Manager (version 2.9.58)
                          - Download Plugins and Themes from Dashboard (version 1.2.0)
                          - Easy Pricing Table (version 1.2.1)
                          - Easy WP SMTP (version 1.3.0)
                          - Enhanced Media Library (version 2.4.5)
                          - Forget About Shortcode Buttons (version 2.1.1)
                          - Go Live Update URLS (version 4.1.5)
                          - Google Analytics Dashboard for WP (GADWP) (version 5.1.2.2)
                          - Google Analytics for WordPress by MonsterInsights (version 6.2.4)
                          - Hello Dolly (version 1.6)
                          - Horizontal scrolling announcement (version 8.7)
                          - Hueman Addons (version 2.0.12)
                          - Import users from CSV with meta (version 1.10.7.5)
                          - Jetpack by WordPress.com (version 5.5)
                          - Logo Carousel (version 1.7.4)
                          - MailPoet 2 (version 2.7.15.1)
                          - MailPoet 3 (New) (version 3.1.0)
                          - Meta Slider (version 3.5.1)
                          - Nav Menu Roles (version 1.9.1)
                          - NextGEN Gallery (version 2.2.14)
                          - Ninja Forms (version 3.2.4)
                          - OneSignal Push Notifications (version 1.16.2)
                          - Pricing Tables (version 1.4)
                          - Regenerate Thumbnails (version 2.3.1)
                          - Sidebar Login (version 2.7.3)
                          - TablePress (version 1.8.1)
                          - TC Pricing Table (version 1.2)
                          - Team Members (version 3.0.1)
                          - TinyMCE Advanced (version 4.6.3)
                          - User Meta Lite (version 1.2.1)
                          - WordPress Importer (version 0.6.3)
                          - WP-Members (version 3.1.9.3)
                          - WP-PageNavi (version 2.92)
                          - WP SimplePop (version 1.8.6)
                          - WP Smush (version 2.7.6)
                          - WP Super Cache (version 1.5.8)
                          - WS Custom Login (version 1.0)
                          - XCloner - Site Backup and Restore (version 4.0.5)
                          - Yoast SEO (version 5.7.1)

# PHP Version:            5.4.45
# MySQL Version:          
# Web Server Info:        Apache

# WordPress Memory Limit: 40MB
# PHP Memory Limit:       128M
# PHP Upload Max Size:    55M
# PHP Post Max Size:      55M
# PHP Upload Max Filesize:55M
# PHP Time Limit:         60
# PHP Max Input Vars:     1000
# PHP Arg Separator:      &
# PHP Allow URL File Open:Yes
# WP_DEBUG:               Disabled

# Show On Front:          posts
# Page On Front:          (#0)
# Page For Posts:         (#0)

**Comment by paconarud** [comment]
any solution?

**Comment by ghost** [comment]
Hi @paconarud this issue is in our list of things to test and fix but we are currently very busy on other devs. We will comment this issue as soon as we test / fix.

**Comment by ghost** [comment]
can't reproduce the problem.
Closed for now.
