### ISSUE TITLE
Topnav logo

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#595]
> Will you please consider adding the ability to add a logo in the top navigation (desktop) in a future update?
> Thank you.

**Comment by ghost** [comment]
![2017-11-19_08-40-28](https://user-images.githubusercontent.com/3038156/32988462-a1f82930-cd05-11e7-8fba-33a6849c7994.png)

**Comment by hosseinfarnia** [comment]
Hi,
any plan to add this feature in the near future?
title or logo in the topbar is excellent like the customizr theme.

**Comment by ghost** [comment]
Closed for the moment
