### ISSUE TITLE
The theme suddenly resets to default setting

### ISSUE THREAD

**Issue by mayazir** [AlxMedia/hueman#600]
The theme suddenly reseted to its default settings.
I even didnt enter to admin panel, just opened the website to check traffic (I use wordfence) and saw all my colors and structure were reseted.
Thanks my clone test website I uploaded 3 days ago I could quickly fix the problem, checking and repeating the settings from my test clone website.
It happened with v3.3.24, wordpress v4.9 
But I also remembered I had the same issue a few weeks ago with my another website with Hueman, and that was v3.3.04 and wordpress v4.6 and I fixed the problem restoring the DB.

**Comment by ghost** [comment]
https://github.com/presscustomizr/hueman/issues/807
