### ISSUE TITLE
Web Page Design - General Design Options - "Fotn"

### ISSUE THREAD

**Issue by gendzo** [AlxMedia/hueman#607]
Small typo :-)
![image](https://user-images.githubusercontent.com/30704878/34376759-d8a3d492-eaed-11e7-9ccc-417820c3e071.png)

**Comment by eri-trabiccolo** [comment]
Hi Gendzo,
thanks for reporting this.
I cannot reproduce it here, might be due to a wrong translation.
What's your locale?

**Comment by gendzo** [comment]
Slovak - sk

**Comment by eri-trabiccolo** [comment]
Weird,
actually there's no translation for the Slovak locale, unless it's translated somewhere else.
Anyway the theme's string is correct:
https://github.com/presscustomizr/hueman/blob/dev/functions/class-utils-settings-map.php#L240

**Comment by gendzo** [comment]
Sorry, my fault, I'm using unoriginal translation from net.
