### ISSUE TITLE
Too Many Redirection Chains : Urgent

### ISSUE THREAD

**Issue by codeslane** [AlxMedia/hueman#611]
Dear @Nikeo, 

I have only 3 plugins but still site loads slowly, when I checked the issue I found too many redirection chains. 

https://dmp.adblade.com/srv/sync/gateway/?cId=zemanta;__src=adblade
https://b1sync.zemanta.com/usersync/adiant/?puid=6507474937080518516
https://stags.bluekai.com/site/23178?id=OH_-SVg ... I2LBNZ2CM5KJMQ6U6SC7FVJVMZZWOBWEYOKTNFRWSWLPOFBQ
https://stags.bluekai.com/site/23178?dt=0&r=918 ... OjC28CZEb/QDlo/0v8ZNHQxZ3AVrmuZ11FxQuYed95YeE5X=
https://b1sync.zemanta.com/usersync/bluekai/cal ... I2LBNZ2CM5KJMQ6U6SC7FVJVMZZWOBWEYOKTNFRWSWLPOFBQ
https://dmp.adblade.com/srv/sync/alias/?cId=zemanta&uId=OH_-SVg6plL9SiciYoqC
https://cm.g.doubleclick.net/pixel?google_nid=spotxchange_dbm&google_cm&google_sc&google_dbm
https://sync.search.spotxchange.com/partner?adv ... 25&uid=CAESEG2zjVAshUioTGkF9854bbo&google_cver=1
https://sync.search.spotxchange.com/partner?adv ... _=1&sync_id=64171bfd-f1ef-11e7-858e-1c02ec4f0003
https://dmp.adblade.com/srv/sync/gateway/?cId=GoogleAdX;__src=adblade
https://cm.g.doubleclick.net/pixel?google_nid=a ... le_cm&google_hm=NjUwNzQ3NDkzNzA4MDUxODUxNg%3D%3D
https://dmp.adblade.com/srv/sync/alias/?cId=Goo ... le_gid=CAESEI3JMdeikwNUyudRtCvjlH0&google_cver=1
https://dmp.adblade.com/srv/sync/gateway/?cId=StoryGize;__src=adblade
https://www.storygize.net/ccm/b04a366f-4651-4172-8e19-92c61cdf2709?u=6507474937080518516
https://dmp.adblade.com/srv/sync/alias/?cId=StoryGize;uId=a5e449b7-1cb0-4df8-82c8-f294f31057fd
https://dmp.adblade.com/srv/sync/gateway/?cId=TripleLift;__src=adblade
https://eb2.3lift.com/xuid?mid=3318&xuid=6507474937080518516&dongle=d13d
https://eb2.3lift.com/xuid?ld=1&mid=3318&xuid=6507474937080518516&dongle=d13d

and many more. 

I think you have implemented sharthis/addthis script in your theme somewhere causing this issue. I'm unable to find those. Please fix this issue. 

Site: https://www.codeslane.com
<img width="1440" alt="screen shot 2018-01-05 at 1 41 58 pm" src="https://user-images.githubusercontent.com/26877201/34600562-3deb258a-f21e-11e7-9168-0ff18ecaca64.png">
<img width="1440" alt="screen shot 2018-01-05 at 1 41 49 pm" src="https://user-images.githubusercontent.com/26877201/34600565-3e172b08-f21e-11e7-8a64-06fd8a362382.png">

**Comment by codeslane** [comment]
@Nikeo 
Please have a look into this.

**Comment by ghost** [comment]
Hi @codeslane, this is not something that the Hueman theme can do.
I would suggest to :

1. disable all your plugins,
2. activate a default theme,
3. remove Hueman
4. re-install Hueman

If the problem persists, you might need to perform a website scan with Wordfence Security to verify that you've not been hacked.

**Comment by codeslane** [comment]
@Nikeo 

I did the following troubleshoot and removing the theme solved the issue but again reactivating the theme caused the same issue.

Had full website scan too, no problem found.

**Comment by ghost** [comment]
Then I would investigate the ads that you have in your widgets

**Comment by codeslane** [comment]
Sure, 

It’s not like everytime but happens randomly and domian waits 60 sec because of that.

I searched for the issue on net and found that addthis & sharethis script cause this issue, but No sharethis or addthis script in header. 

Before the latest update of the theme, everything worked smoothly. 🙁🙁
