### ISSUE TITLE
Amazon ad doesn't correctly show up in the header widgets

### ISSUE THREAD

**Issue by eri-trabiccolo** [AlxMedia/hueman#612]
code example to place in a custom html widget in the header widgets area.
`<script src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&amp;adInstanceId=5a041e25-c8bb-439f-acde-d4aa3792dace"></script>`

t really seems that the amazon ad widget script doesn't "like" that place, it's not able to calculate the space it can take (mostly because of the floating right of the header-widgets block), ending up to not display at all.
​reported here:
https://secure.helpscout.net/conversation/501537078/36362?folderId=607709

Not sure what we can actually do for this...

**Comment by ghost** [comment]
OK thx for reporting.
At least we know it's limited to a specific widget zone.
