### ISSUE TITLE
Blog page should allow users to display several grids of posts sections based on categories

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#613]
> I'm currently using your free hueman theme and won't mind buying premium if it'd satisfy my needs.Most especially, I want to be able to select which categories or tags would appear in homepage, different sections.Such that I can have different category for slider and immediate posts,another category such as "exhibition" under...And another category, called blog, under and so on

--

**Comment by eri-trabiccolo** [comment]
Yeah if we had a builder or a widgetized home or a page template doing that.
Also I guess these posts should be displayed in different layouts.

**Comment by ghost** [comment]
will be addressed by the grid module with Nimble : https://github.com/presscustomizr/nimble-builder/issues/174
