### ISSUE TITLE
Feature request: Exclude category from post list on homepage

### ISSUE THREAD

**Issue by denzelchia** [AlxMedia/hueman#622]
Hi @Nikeo and @eri-trabiccolo 

Customer on helpscout make a request to have option to exclude category / categories from post list on homepage.
https://secure.helpscout.net/conversation/510633819/36912?folderId=607544

Thank you
Denzel

**Comment by ghost** [comment]
Tnx for reporting.
It could be implemented like the customizr's category filter.
We actually would need two filter types : include and exclude.
Or a simple one item CRUD module in which we could pick a condition ( including, excluding ) + a category or a tag
