### ISSUE TITLE
Feature request: Allow a way to sticky a post in feature posts slider ( featured category )

### ISSUE THREAD

**Issue by denzelchia** [AlxMedia/hueman#624]
Hi,

Customer on helpscout made a request to provide a way to stick a post to the top of the selected featured category in the featured posts slider.

Please refer to details in the helpscout ticket
https://secure.helpscout.net/conversation/510944321/36943/?folderId=607544

Thank you
Denzel

**Comment by eri-trabiccolo** [comment]
@Nikeo customer's waiting for a reply.
:)
