### ISSUE TITLE
Featured request: Add option to change image size in Feature Posts slider

### ISSUE THREAD

**Issue by denzelchia** [AlxMedia/hueman#625]
Hi,

Customer on helpscout made a request to provide an option to change the image size in the featured posts slider.

Please refer to details in the helpscout ticket
https://secure.helpscout.net/conversation/510944321/36943/?folderId=607544

Thank you
Denzel

**Comment by eri-trabiccolo** [comment]
@Nikeo customer's waiting for a reply.

**Comment by ghost** [comment]
@denzelchia @eri-trabiccolo thanks for reporting this. Sorry for the delay I was travelling the last two days. No there's no plan to change this image size.
