### ISSUE TITLE
Dynamic tab issue

### ISSUE THREAD

**Issue by hosseinfarnia** [AlxMedia/hueman#626]
Hi,
Dynamic tab widget is deleted and reset to default settings after changing the theme to something else. I mean after activating the theme this happens.

**Comment by eri-trabiccolo** [comment]
Hi there,
thanks for reporting this.
I've been able to reproduce this issue partially.
When switching to another theme and then back to the Hueman theme, the dynamic tab widget was "removed" from its previous sidebar location, but still present under the Inactive Widgets, without losing the settings.
