### ISSUE TITLE
Feature request: Adding safe area inset support for iPhone X

### ISSUE THREAD

**Issue by denzelchia** [AlxMedia/hueman#631]
Hi @Nikeo and @eri-trabiccolo

Please refer to the following helpscout ticket.
https://secure.helpscout.net/conversation/514067900/37148/?folderId=607544

Customer request to add safe area inset support for iPhone X, so that content does not get obscured by the shape of the screen.

I have no prior knowledge about iPhone X "safe area inset" until I come across the following web page.
https://webkit.org/blog/7929/designing-websites-for-iphone-x/

Thank you
Denzel

**Comment by ghost** [comment]
closed, for the same reasons explained here : https://github.com/presscustomizr/customizr/issues/1437
