### ISSUE TITLE
Tooltips for social media icon in sidebar goes behind the sidebar toggle when viewing in iPad.

### ISSUE THREAD

**Issue by denzelchia** [AlxMedia/hueman#632]
Hi @Nikeo and @eri-trabiccolo 

A user on WordPress.org reported this issue.
https://wordpress.org/support/topic/hover-popup-explainer-showing-behind-sidebar-header/

I am able to replicate it when viewing user's site in browser responsive design mode.
https://screencast-o-matic.com/watch/cFnVVaoyH7

Thank you,
Denzel

**Comment by robinckarlsson** [comment]
Hi @Nikeo and @eri-trabiccolo (and @denzelchia)

This issue persists, could you please have a look?

Thanks
Robin

**Comment by plimfec** [comment]
Hi there,

I came across this same problem (social media tooltips hidden behind the sidebar header) in fresh Hueman 3.4.5. Tried to solve it with CSS, playing with z-indexes, but didn't get it done. Could you please investigate this for the next release?

Thanks,
Plimfec 

---

Btw, I got the chance to check this issue in old Hueman 3.3.4 as well. In that version this problem didn't exist yet.

**Comment by ghost** [comment]
addressed in https://github.com/presscustomizr/hueman/issues/731
