### ISSUE TITLE
The icon sidebar toggle ( << ) looks like it got the wrong padding (only at screen size 719px or smaller). 

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#641]
https://wordpress.org/support/topic/hueman-3-3-27-problems-sidebar-toggle-comment-count-and-social-media-icons/#post-9965353

> The icon sidebar toggle ( << ) looks like it got the wrong padding (only at screen size 719px or smaller). Besides this it looks too big and heavy to me in this new version, but I guess that’s personal taste.

**Comment by eri-trabiccolo** [comment]
Padding wrong, right.
"Big and heavy", yeah, unfortunately we knew it.
This:
https://github.com/presscustomizr/hueman/blob/dev/assets/front/css/dev-responsive.css#L175

should be 
`padding:10px 0;`
