### ISSUE TITLE
Probable Overlapping bug

### ISSUE THREAD

**Issue by emran1** [AlxMedia/hueman#642]
Ticket: https://secure.helpscout.net/conversation/518813047/37488/

Our demo also reflects the overlapping if we check on a small monitor by reducing the size of the browser window on "learning more about post:

http://prntscr.com/idwxt7

https://demo-hueman.presscustomizr.com/learning-more-about-macaws-in-the-amazon-jungle/

**Comment by ghost** [comment]
@emran1 thank you for reporting the problem.
After a page reload on the page, the problem went away. It seemed that the fittext.js ( javascript library in charge of the adaptative font-size) was not triggered at first.
Let me know if you still can reproduce the problem on the same demo page ?

**Comment by emran1** [comment]
@Nikeo Thanks for checking and precisely I'm also now able to see it fine and just replied to the user as well.
