### ISSUE TITLE
adding a Breadcrumb?

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#643]
As requested by a user
> category name above post title in single page is better to be breadcrumbs home >category>post title it is better for users and SEO and that make easier site navigation

The idea would be to adapt the existing Customizr breadcrumb

**Comment by eri-trabiccolo** [comment]
Makes sense, but "category name above post title in single page" are actually hierarchical taxonomies, what we call post-metas in Customizr - meaning that they can be more than one, while the breadcrumbs will show just one of them (at most).
So yeah, let's put the breadcrumb there, but then we need another place where to show the "categories" (optionally) maybe.

**Comment by ghost** [comment]
yep I agree, for the moment we'll use the features of the customizr breadcrumb
