### ISSUE TITLE
How about an option for collapsible submenus in mobiles ?

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#645]
Like we did for the Customizr theme
https://github.com/presscustomizr/customizr/issues/1204
https://github.com/presscustomizr/customizr-front-js-parts/pull/23

@eri-trabiccolo let's discuss this during our next dev point

**Comment by codeslane** [comment]
+1

**Comment by ghost** [comment]
Hi @eri-trabiccolo let me know if we're good for the specs

**Comment by ghost** [comment]
Hi @eri-trabiccolo let me know if we're good for the specs

**Comment by eri-trabiccolo** [comment]
I think we are :D

**Comment by ghost** [comment]
ok

**Comment by ghost** [comment]
this also applies to the footer menu

**Comment by eri-trabiccolo** [comment]
Hueman: https://github.com/presscustomizr/hueman/pull/662
front js fmk: https://github.com/presscustomizr/themes-front-js-fmk/pull/1
front js part: https://github.com/presscustomizr/hueman-front-js-parts/pull/2
ha front css part: https://github.com/presscustomizr/hueman-pro-addons/pull/139

Example of how it would look like in the header mobile menu
<img width="301" alt="2018-03-09_11-37-02" src="https://user-images.githubusercontent.com/7689242/37206487-13737efe-2399-11e8-945f-6c5344406c14.png">
(similarly for the footer menu)

**Comment by eri-trabiccolo** [comment]
requested here:
https://secure.helpscout.net/conversation/611175549/163889?folderId=607541

Though I'm not very convinced about the border that surrounds the dropdown button, which might be ugly with custom menu item font sizes.

If you agree I would alter the PR removing it next monday.

**Comment by ghost** [comment]
Ah yes I wanted to merge your PR for the latest release.
Will be part of this week's release.

About the borders, yes I agree let's remove them.
Thanks !

**Comment by eri-trabiccolo** [comment]
Border removed
