### ISSUE TITLE
Global $content_width is not properly set

### ISSUE THREAD

**Issue by eri-trabiccolo** [AlxMedia/hueman#649]
## Problem
Here:
https://github.com/presscustomizr/hueman/blob/v3.3.27/functions/init-after-setup-theme.php#L7

the `$content_width` is set, but that's a `global` variable so it should be:
`
global $content_width;
if ( !isset( $content_width ) ) { $content_width = 720; }
`
or
`if ( !isset( $GLOBALS['content_width'] ) ) { $GLOBALS['content_width'] = 720; }`

To be honest it wouldn't actually check whether is set or not, it's the theme content_width! :D 

Would be even better, IMHO, to set a default content_width that should be overridden once the columns layout (waiting for skope) is set [advanced, maybe in the future].

## Why this can be "important"
Mostly for plugins compatibility e.g. the Jetpack's tiled gallery uses that value as default width for the gallery rows. Note: the jp js, when you use a content_width greater than the actual available width, will set the gallery-rows width to the maximum available width; weirdly enough it doesn't do the opposite.
This issue has been reported here:
https://wordpress.org/support/topic/gallery-not-centered-when-two-columns-content-left-design-used/

**Comment by ghost** [comment]
thanks for reporting !
totally right
