### ISSUE TITLE
Display both logo and site title together

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#657]
https://secure.helpscout.net/conversation/531093298/38306?folderId=610156

**Comment by agicquel** [comment]
No plan for this feature yet ?

**Comment by ghost** [comment]
## Spec
- displayed in addition to the logo only when a checkbox is checked
- a new setting + control to be added ( like in Customizr ) => disabled by default, for all users.
- the site title will be displayed above the tagline ( when the tagline is displayed )
- the vertical centering between logo - tagline + site title will be implemented with flex

## behaviour
if no logo => site tile
if logo => logo and no site title
if logo and new option checked => logo + site title
