### ISSUE TITLE
H2 is the same size as H1

### ISSUE THREAD

**Issue by hosseinfarnia** [AlxMedia/hueman#658]
Hi,
I think that H2 is the same size as H1 or it is just a little smaller.
I think this only happens when the layout is set to two colums.
for example, please take a look at this post:
https://windowsmag.ir/how-to-find-out-programs-slowing-down-windows-10-boot/
Thank you

**Comment by mayazir** [comment]
Change the font-size inside .css
Very easy

**Comment by mayazir** [comment]
Change the font-size inside .css
Very easy. 
Just dont forget to add !important

**Comment by hosseinfarnia** [comment]
Thank you @mayazir 
That was very nice of you to mention it.
