### ISSUE TITLE
Implement the option "Apply a category filter to your home / blog posts"

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#659]
Like in the Customizr theme
Doesn't have to be dependant on the category defined for the Featured Posts, if any.
![2018-03-06_16-32-33](https://user-images.githubusercontent.com/3038156/37046404-8fd0a7e8-2168-11e8-8764-be8e429e45f5.jpg)

**Comment by eri-trabiccolo** [comment]
also requested here:
https://secure.helpscout.net/conversation/557743145/39445?folderId=607709

**Comment by ghost** [comment]
also requested here : https://secure.helpscout.net/conversation/747710315/167020/?folderId=607541

**Comment by eri-trabiccolo** [comment]
see: https://github.com/presscustomizr/hueman/pull/744
**NOTE:** as for Customizr classic grind when using the classic style, we need to disable this feature when the infinite scroll is enabled, see:
https://github.com/presscustomizr/hueman/pull/744/files#diff-23aa52da537288b4c922b47a7d325d63R1828

I've added a note in the control notice to inform the user about that:
https://github.com/presscustomizr/hueman/pull/744/files#diff-a979707592bbbf8b1d93c23acbd4b93eR1014
