### ISSUE TITLE
Early check on php version ( must be >= 5.3 ? ) + WP version ( must be >= 4.6 )

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#665]

**Comment by eri-trabiccolo** [comment]
Mmm, well the thing would be what to do in front.
In admin I can display a notice but in front... I cannot really display anything...

It will then go this way.
In admin we display a notice,
In front a blank page or a php error might happen (wp still loads the theme templates that will try to call undefined functions)

**Comment by ghost** [comment]
ok let's go this way for the moment. We'll figure out a better way (if any possible ) in the future.
