### ISSUE TITLE
Implement gutenberg post-format metaboxes visibility compatibility

### ISSUE THREAD

**Issue by eri-trabiccolo** [AlxMedia/hueman#672]
see https://github.com/presscustomizr/customizr/pull/1500

**Comment by eri-trabiccolo** [comment]
Looks like the fix for this issue has never been merged,
actually I think I never opened a PR.
In any case the PR must be amended as that code doesn't work anymore.
I have a rapid patch for it involving a timeout (300ms) to be quite sure Gutenberg did its rendering job so that the post-formats selector has been created (dom element) and we can refer to it.
A more in depth study of the Gutenberg code might be needed.

Since this is not critical, let's go with a rapid patch

**Comment by ghost** [comment]
OK.
It would be good to attach those actions to a Gutengerg event. ( if it was documented... )

**Comment by eri-trabiccolo** [comment]
Would be even better if we could use two different js depending on which editor we're on (if it was documented...)

**Comment by ghost** [comment]
ah yeah, true
