### ISSUE TITLE
header advertisment covers header banner in mobile

### ISSUE THREAD

**Issue by hosseinfarnia** [AlxMedia/hueman#674]
Hi,
In mobile Devices when header advertisement is shown, it goes over header banner and header banner can not be seen.
like: https://windowsmag.ir

**Comment by hosseinfarnia** [comment]
Hi Dear Staff,
I have set two advertisements on header for test and in mobile devices the header image can not be seen, and it is really messy.
Please take a look at it to see what the problem is.
I also have a suggestion to deactivate header image for tablet or mobile and smaller devices. because in this devices the header image becomes so small and maybe some people prefer not to display it.
Thanks a lot

**Comment by mayazir** [comment]
try add class or id to the ads area and use width-max or width-min to relocate the ads in mobile layout

**Comment by mayazir** [comment]
by the way, how did you get the "list" style on category?
i have grid on category and it is ok for me, but I need "list" for blog.
http://mexicanroutes.com/category/resorts-beaches/ - this one is ok.
http://mexicanroutes.com/category/blog/ - but here I need list and not grid

**Comment by hosseinfarnia** [comment]
Hi
it is easy to set the list style.
when you are on your blog page, click Customize on the wordpress topbar and then go to Main body design and go to POST LIST DESIGN section and choose Standard list for your blog page.
if it can not be applied, you must check the Advanced Options>Hueman Admin Settings and here Enable a "per page" customization.
this them has the ability to choose a different style for every page. for more information you can read the documentation of the theme.

**Comment by mayazir** [comment]
thanks, but then I change all category layout and I want list category just for BLOG category.
Not for BLOG as blog template page, I use BLOG category for Blog.
I want the rest category as grid and just one category as list...

**Comment by hosseinfarnia** [comment]
Hi
sorry, I am a little confused and can't understand what you want, otherwise I would helped you.
You can ask this question on the free forum. there are more professional guys like Emran and Denzel that can help you better.
here the developer team has no support.
