### ISSUE TITLE
Feature Request: standard list with boxed layout

### ISSUE THREAD

**Issue by hosseinfarnia** [AlxMedia/hueman#675]
Hi Nicolas,
I just bought the hueman pro. It is really fantastic as everybody says. I wish I had bought it sooner.
But At first I thought that the standard list is displayed as boxed layout like post grids, and thumbnail placeholders can be disabled. But it was not.
Would you please add boxed layout with shadows to standard list just like the post grids and with the ability to hide thumbnail placeholders in standard list.
I really like this boxed layout for standard list.
please take a look at my website and see how simple and messy it is when you disable thumbnails.
https://windowsmag.ir
Best Regards
Hossein

**Comment by emran1** [comment]
@Nikeo User's insisting on a ticket for the feature to add asap. Thanks.

**Comment by hosseinfarnia** [comment]
hi,
I think another good option for adding this feature is just adding 1 column to Max number of columns on masonry grid. I think after setting max number of columns to 1, the post list design will look like standard list.
