### ISSUE TITLE
Test v3.3.28

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#684]
https://github.com/presscustomizr/hueman/releases

### Notes
The changes are not significant and don't impact critical parts of the code.
- removed previewer dummy content and image
- removed welcome note
- removed help icon link in the admin bar

The build has been manually done because of the current work in progress on the czr framework and contextualizer.

### Tests to do
- [x] run Theme check
- [x] run the customizer preview when another theme is active
- [x] update an already customized Hueman site with this release. Check for any problem in admin / front / customizer

**Comment by eri-trabiccolo** [comment]
tests passed on my side.

**Comment by ghost** [comment]
on my end too.
