### ISSUE TITLE
[Feature request] Stick content column?

### ISSUE THREAD

**Issue by eri-trabiccolo** [AlxMedia/hueman#687]
https://wordpress.org/support/topic/glue-to-bottom-sidebar-option-2/

I'm not sure what's the actual meaning of "glue to bottom sidebar", maybe it means stick the main content column to top when the content's height is smaller than the sidebar one(s)?

**Comment by ghost** [comment]
I think it means that instead of waiting the end of a long page to see the rest of the glued sidebar, the sidebar scrolls at the start like the content, and glues to the bottom at some point, if smaller than the content. <= which is kind of the opposite current behaviour.
related #448

**Comment by eri-trabiccolo** [comment]
Ah ok, so I just don't understand why it should glue to the bottom at some point, but ok.
I thought having the content sticky would have made more sense  :D
