### ISSUE TITLE
Search form bug

### ISSUE THREAD

**Issue by mayazir** [AlxMedia/hueman#689]
For example I have a post named "Mexico City" and a lot of related posts where the same words "Mexico City" appear in title, but when I search for "Mexico City" I get a lot of posts BEFORE the right post.
Try to search "Mexico City" on my website to see it..
http://mexicanroutes.com/towns-cities/
Use the search form in topbar menu, because the content search is plugin, but both of them work the same way - never dhispaly as first result the right post 100% matching with the request.
How could I solve it?
Any code lines to add?
I need first appears the 100% match result and then the rest in a-z order..

**Comment by eri-trabiccolo** [comment]
Hi there,
actually the search is performed by WordPress and this theme doesn't alter it, with two exceptions:
1) Includes custom post types to the search results -> but looking at your site, searching for "Mexico City" I don't see custom post types.
2) Includes attachments in the search results, if you have this option enabled:
Appearance -> Customize -> Advanced options -> Include images in search results
which is disabled by default.

Did you test the search functionality with any other WordPress theme, like the standard Twenty Seventeen?
Do you get a different result?
