### ISSUE TITLE
SVG support???

### ISSUE THREAD

**Issue by elliot-labs** [AlxMedia/hueman#69]
Are you able to add svg support to your theme? It would be nice to be able to display svg images as featured images and in posts...

**Comment by hibosko** [comment]
Hi elliot! try this plugin: https://wordpress.org/plugins/svg-support/ works great for me! ;)

**Comment by elliot-labs** [comment]
@hibosko 
I figured it out: Add the mime type to the apache server. This adds server support for and allows me to display them. Previewing (before they are attached) them is an entirely different matter. That I have not figured out yet.

Thanks for the tip!
