### ISSUE TITLE
Plugin conflict: Yoast Seo

### ISSUE THREAD

**Issue by emran1** [AlxMedia/hueman#696]
https://secure.helpscout.net/conversation/635807119/164622/

**Comment by eri-trabiccolo** [comment]
Cannot reproduce the issue with Yoast SEO and the Hueman-Pro (or hueman-addons) sharing buttons.
Can you @emran1 ?
Can you @Nikeo ?

**Comment by mayazir** [comment]
yoast seo is completely useless plugin, use all-in-one-seo plugin.
