### ISSUE TITLE
Width of image inside the content of fetured posts, displayed in a slider, should not be set to 100%

### ISSUE THREAD

**Issue by eri-trabiccolo** [AlxMedia/hueman#703]
https://secure.helpscout.net/conversation/683498965/165599/#thread-1901174375

This is due to:
https://github.com/presscustomizr/hueman/blob/v3.4.5/assets/front/css/_parts/2_0_flexslider.css#L24

I guess the main aim of this rule is to target the post thumbnail image, not all the images in the slides content.

**Comment by ghost** [comment]
OK thanks.
We'll discuss it during our next dev chat.
