### ISSUE TITLE
theme auto reset (not the first time bug)

### ISSUE THREAD

**Issue by mayazir** [AlxMedia/hueman#710]
This is not the first and also not the second time I have this problem.
My website suddenly lose all personalization: tab color, header, footer etc.. all are reseted..
I reupload all backup files, but nothing helped.
I dont remember how I solved it before, I remember I just manually reconfigurated all theme.
So, each time the theme reseted I have to begin to search and solve it..
I dont understand where is the bug, but this is not the first time..
I still have my personalized CSS, but the rest of theme are reseted to default...

**Comment by Amitind** [comment]
Always customize child theme, not main theme,
You should look at here
https://codex.wordpress.org/Child_Themes

**Comment by mayazir** [comment]
I didnt mean I lost all my CSS files.
The problem is the theme itself gets reseted.
I mean where you enter into Customization and acvite/desactive theme opions.
I have all edited .php saved on my PC, the problem is not edited .php files.

**Comment by mayazir** [comment]
I already solved it I hope, I check my old screens on waybackmachine and recreated all design.
The website is http://ancientmayanruins.com
And this is not the first time I have this problem.
Look at sidebars, the left one is the same color as in default theme, but the right sidebar has personalized color, and this color was reseted to the default one.
Also footer color was gone, my logo changed size, the footer copyright and menu were reseted to default ones, left sidebar had no social network icon, all posts got "next" button on the left sidebar and not below the post etc....

**Comment by ghost** [comment]
@mayazir thanks for reporting the bug.  Looking at your site's code, you seem to use a theme based on Hueman v3.3.25.
I would recommend to update the Hueman theme to the latest version and port all your customizations in a child theme. Because this problem of options being reset randomly is something that could occur before in some conditions, but that has been fixed now.

@eri-trabiccolo this looks an old problem we had long time ago when handling our default options.

**Comment by mayazir** [comment]
Sorry, but very bad work. 
My theme got reseted again and this time on my more complicated website - MexicanRoutes.com
All my 2 years work got lost...
"thanks" you very much... I am already 2 hours awake and still didnt got even 50% of modifications..

**Comment by mayazir** [comment]
the same happend with my another website - MexicanRoutes.com
I lost more than 2 hours to get the same design as before.

**Comment by mayazir** [comment]
@Nikeo, could you explain if it possible to make backup just of "customization" config?
I cant now to update the theme version because I need to edit a few .php and check if this new version have no problem with the rest of plugins and edited lines and it takes time.
Could you make some patch for just backup "customization" of the theme?
Or explain where this info saved?

**Comment by mayazir** [comment]
I also have problem with child theme. 
I created a child theme and it works just with css but not with all php I put inside, so I dont use child theme.
I put all edited php into a folder, so each time you make update, I open that folder and check all edited php and edit the same way all new version"s php.
There list of all edited php:
footer.php
functions.php
header.php
sidebar.php
sidebar-2.php
tmpl/archive-tmpl.php
tmpl/single-tmpl.php
I dont know what I do wrong, but just css really works from child theme, the rest pho dont

**Comment by ghost** [comment]
https://github.com/presscustomizr/hueman/issues/807
