### ISSUE TITLE
Gutenberg 4.1.1 Youtube fills entire page - Responsive

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#711]
https://secure.helpscout.net/conversation/694038989/165819/?folderId=607544

following #708 

> Hi there
> 
> I reported the previous bug with Gutenberg 4.0 and the giant space over any Youtube video in articles created in Gutenberg. http://Giant space above all Youtube video in Posts #10109
> 
> Now Gutenberg have made changes and now the the Youtube video takes over the entire page: See Gutenberg error ticket I logged here:
> 
> https://github.com/WordPress/gutenberg/issues/11085
> 
> Please assist.
> 
> Thank you :)

> And later
> 
> Hi there This is what Wordpress says: I tested with WordPress 4.9.8 and Gutenberg 4.1.1 and the Twenty Seventeen 1.7 theme using Chrome 70.0.3538.77 on macOS 10.13.6 and I do see wp-embed-aspect-16-9 wp-has-aspect-ratio getting added to the Settings > Block > "Additional CSS Class" field and I think that is the expected behavior. Videos look good in my test and don't explode to fill the page as you described. Recent work has been done to remove gaps that were appearing around some videos and to change the way responsive videos work whether or not the theme opts in using add_theme_support( 'responsive-embeds' ); (reference). Note: if a theme has opted in, you would see a "Media Settings" panel in the sidebar for the YouTube block (screenshot). It's possible the Hueman Pro have been working around this or have a separate solution or that the latest update makes a change they didn't anticipate. It would be worth letting the Hueman Pro theme authors know:
> Recent changes were made to make responsive embeds a theme option at #10477
> Does the problem happen for new posts you create after upgrading to 4.1+ or posts that previously had YouTube embed blocks or both?
> Steps to reproduce the problem.
> Note whether you have any other active plugins which could be interfering with how videos (just in case).
> Can you please come back to me on this issue. I have updated to the latest version of Hueman Pro and I still have this problem. Kind regards Deborah

**Comment by ghost** [comment]
@eri-trabiccolo to be discussed. related to #708

**Comment by ghost** [comment]
I'll be back Friday afternoon

**Comment by eri-trabiccolo** [comment]
Well I fixed that in #709 :)

**Comment by ghost** [comment]
fixed in #709 pr
