### ISSUE TITLE
the_title() => the_title_attribute() ?

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#713]
> Dear support,
> 
> According to wp-Typography plugin, Hueman Pro is using an improper function to set the title attribute.
> 
> More likely than not, your WordPress theme is using an improper function to set the title attribute of your heading's link. It is probably using the the_title() function, which delivers the post title afterfiltering. It should be using the_title_attribute() which delivers the post title before filtering. Change out this function throughout your theme when it is used inside of an HTML tag, and the problem should go away.
> 
> I have updated the code in my child theme, which seems to work, would you please consider taking this into account when you update your theme?
> 
> Thank you.

**Comment by ghost** [comment]
@eri-trabiccolo to be dicussed

**Comment by eri-trabiccolo** [comment]
Makes sense, not that improper as long as you escape it... but ok :)
