### ISSUE TITLE
<link rel="profile" href="http://gmpg.org/xfn/11" /> should be made ssl compliant

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#714]
Reported here : https://secure.helpscout.net/conversation/701721413/165982/

Solution : use set_url_scheme()

> there is in html-header a link to profile gmpg.org
> 
> I deleted it, cause the link wasn't https
> 
> 
> so please change the link to https or remove this profile-tag. Or add an option, to remove it in wp-admin.
> 
> 
> thanks from Switzerland

**Comment by eri-trabiccolo** [comment]
Ah,
for Customizr too.

Though that doesn't bring to any ssl warnin.

Anyway we don't need the set_url_scheme() thing, as it doesn't depend on the secure protocol of the website where Hueman runs.
We just have to write it statically here:
https://github.com/presscustomizr/hueman/blob/dev/header.php#L6
as
`<link rel="profile" href="https://gmpg.org/xfn/11">`

no need to use the `esc_url` either IMHO

**Comment by ghost** [comment]
ah yeah that's right, hard writing it is enough !

**Comment by ghost** [comment]
I'm fixing it on both themes

**Comment by eri-trabiccolo** [comment]
remember that Customizr has it 2 times :D 

https://github.com/presscustomizr/customizr/blob/dev/inc/_dev/parts/class-header-header_main.php#L123
https://github.com/presscustomizr/customizr/blob/dev/templates/head-no-model.php#L13
