### ISSUE TITLE
Consider adding a sidebar color option

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#718]
https://secure.helpscout.net/conversation/703126456/166010?folderId=607547

Spec
- the option would be located in Main Body Design > sidebar. Below the top boxes checkbox.
- the default color is #f0f0f0
![2018-11-09_15-25-28](https://user-images.githubusercontent.com/3038156/48267888-c686fb00-e433-11e8-9e80-9641bb59852d.jpg)

**Comment by ghost** [comment]
@eri-trabiccolo we did not discuss it during today's chat. But would it be possible that you work on that next week ?

**Comment by eri-trabiccolo** [comment]
are we talking about sidebars ~~text~~ background color? mmm #f0f0f0 is ~~red~~ gray
I will look at it, but actually the problem with hueman is that it has an image as background of the central column...

**Comment by ghost** [comment]
#f0f0f0 is grey to me..., well it's the one that we currently have as default if you want.

> .sidebar .sidebar-content, .sidebar .sidebar-toggle {
>     -webkit-transform: translate3d(0,0,0);
>     -moz-transform: translate3d(0,0,0);
>     -o-transform: translate3d(0,0,0);
>     transform: translate3d(0,0,0);
>     background: #f0f0f0;
> }

**Comment by eri-trabiccolo** [comment]
ahah yes sorry, I corrected, the comment.
That's the image I was talking about:
<img width="958" alt="2018-11-09_15-52-24" src="https://user-images.githubusercontent.com/7689242/48269312-8e81b700-e437-11e8-86ca-d916686b07cc.png">

You know... we can set the background of the sidebar A, but when the main content (or another sidebar) is bigger than the sidebar A, there will be that "grey background" below...

I will see to replace that image with some pure CSS code, using pseudo elements if needed!

**Comment by ghost** [comment]
yes this could be improved in the future. Let skip it for now.
Fixing this might require additional html.

**Comment by eri-trabiccolo** [comment]
here's a PR with the pseudo elements and got rid of the background images:
https://github.com/presscustomizr/hueman/pull/725
I think it's fine, and reproduces the same style we had before, with this small difference:
<img width="79" alt="separator" src="https://user-images.githubusercontent.com/7689242/48628845-715d6300-e9b8-11e8-8334-8880f7c41963.png">
(in tablets, when both sidebars are collapsed, the background image had a line that seemed a separator, I haven't reproduced it using pseudo-elements)

here's the one without the pseudo elements, keeping the background images:
https://github.com/presscustomizr/hueman/pull/726

To be honest I don't think the second is a good solution, it adds this new option but doesn't really make it usable.

**Comment by ghost** [comment]
OK good work for #725. I agree looks better. Hopefully, the sidebars width is not customizable ...

**Comment by eri-trabiccolo** [comment]
Yeah it is not customizable, but ... in any case the current implementation relies on the fact the sidebar widths are not customizable.

**Comment by ghost** [comment]
yes absolutely. And this is not planned.

**Comment by ghost** [comment]
I'll go with #725
