### ISSUE TITLE
Hueman theme still resets 

### ISSUE THREAD

**Issue by mayazir** [AlxMedia/hueman#740]
The theme continue to reset to default settings.
I lost all "customization" again.
It resets all the time...

**Comment by mayazir** [comment]
I just cant understand, or the author makes the theme or doesnt make the theme if he cant make it right way. I have to check the website each day, each hour. Because when the "customization" gets reset the website lose all design.... I mean at least hour to recover all... Each time the same bug... all versions

**Comment by hosseinfarnia** [comment]
I had the same problem after updating the theme.
I think this theme should have an option to export and import the customizations.
This theme has too many customizations and setting them each time takes a lot of time.

**Comment by mayazir** [comment]
I dont remember from what version it has reset.. 
Try this plugin for backup customizations: https://wordpress.org/plugins/customizer-export-import/
But the problem is not set it back, but to be always on alert and check the website all the time...

**Comment by mayazir** [comment]
I dont remember from what version it began to reset..
Try this plugin for backup customizations: https://wordpress.org/plugins/customizer-export-import/
But the problem is not set it back, but to be always on alert and check the website all the time...

**Comment by hosseinfarnia** [comment]
Thanks @mayazir  for introducing the plugin.

**Comment by ghost** [comment]
https://github.com/presscustomizr/hueman/issues/807
