### ISSUE TITLE
Test with php 7.3 ?

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#742]
@eri-trabiccolo can you confirm that you have no troubles when testing the Hueman theme with the latest version of php ? https://secure.php.net/downloads.php
to be discussed today
thx

**Comment by eri-trabiccolo** [comment]
I've tested it with VVV, I'm currently using php73 nginx_upstream for my local test website.
Cannot see any issue, atm.

**Comment by ghost** [comment]
thanks
