### ISSUE TITLE
Allow default thumbs to be overridden in a child-theme?!

### ISSUE THREAD

**Issue by eri-trabiccolo** [AlxMedia/hueman#746]
https://secure.helpscout.net/conversation/760186744/167357?folderId=607709

@Nikeo 
I think we can, not a big deal. Waiting for your decision to reply...

**Comment by eri-trabiccolo** [comment]
@Nikeo ^

**Comment by ghost** [comment]
thanks for the reminder.
If this had to be implemented, it would be as an option in the customizer. but this is not a priority right now.

**Comment by ghost** [comment]
I'm following up by email

**Comment by eri-trabiccolo** [comment]
I actually meant just look into the child-theme folder before, but ok I see your point :)
