### ISSUE TITLE
Sidebar icon toggles: namespace their CSS class name to avoid conflicting plugins issues

### ISSUE THREAD

**Issue by eri-trabiccolo** [AlxMedia/hueman#749]
reported:
https://wordpress.org/support/topic/sidebar-toggle-display-on-mobile/

The issue seem to be due to a plugin which is styling all the 
`[class^=icon-]:before, [class*=" icon-"]:before`
with a different font-family (and other stuff).
and our toggler class is `icon-sidebar-toggle`

**Comment by ghost** [comment]
OK thanks for reporting.
Assigning it to your column, in the Hueman group
