### ISSUE TITLE
Change Sidebar titles

### ISSUE THREAD

**Issue by elliot-labs** [AlxMedia/hueman#75]
Since you added the option to toggle the sidebar title box, can you add the ability to change the sidebar title box's text?

Thanks!

**Comment by AlxMedia** [comment]
The best way to do this is to simply modify the /languagues/en_US.po file to say what you want it to say, instead of changing it via fields in admin. It has to do with compatibility with plugins etc - better to leave it there IMO. Thanks for the suggestion though!

**Comment by elliot-labs** [comment]
I understand "for plugin compatibility" (simple answer) but could you go into a little more details?

Thanks!
