### ISSUE TITLE
Custom taxonomy/post type archive titles not correctly displayed

### ISSUE THREAD

**Issue by eri-trabiccolo** [AlxMedia/hueman#750]
The first cpt title of the list is displayed instead.
This has been reported here:
https://wordpress.org/support/topic/strange-heading-for-custom-tax-archives/

Ad the user reports, the title is displayed with an h2 tag, this means that, reasonably excluding this:
https://github.com/presscustomizr/hueman/blob/v3.4.12/parts/page-title.php#L4-L5

the following condition is met:
https://github.com/presscustomizr/hueman/blob/v3.4.12/parts/page-title.php#L27-L28

And `the_title()`, there, as we know, will return the first post title in the archive.

What we need is some additional checks on the nature of the query, as we do, for example in the Customizr theme:
https://github.com/presscustomizr/customizr/blob/v4.1.26/core/front/models/content/post-lists/headings/class-model-archive_heading.php#L39-L45

**Comment by ghost** [comment]
ok. thanks
this is a spec.
Let's implement it. In your column.

If ok with you, can you inform the user that we're on it ? you can provide a vague deadline like the next release.
