### ISSUE TITLE
Plugin conflict: Disqus comment plugin

### ISSUE THREAD

**Issue by emran1** [AlxMedia/hueman#754]
https://secure.helpscout.net/conversation/768159193/167600?folderId=607541

**Comment by eri-trabiccolo** [comment]
I've investigated a little more into this, through the [disqus system plugin](https://it.wordpress.org/plugins/disqus-comment-system/).
Basically the comment count is handled via PHP + js, the js part is responsible for the replacement of the "WordPress" comments count with the disqus one... but it requires a that a "span" added by the PHP part (which hooks to the 'comments_number' hook filter) is a direct child of a link.
This is true in single posts -> https://github.com/presscustomizr/hueman/blob/v3.4.12/parts/page-title.php
But not in our list of posts -> https://github.com/presscustomizr/hueman/blob/v3.4.12/content-standard.php#L12
where, as you can see, the comments_number() is wrapped in an additional span.

Need to find a good way to not disrupt our "comment bubble" ui.

Of course this is not a specific theme's fault, but rather... well it's clear.

**Comment by ghost** [comment]
ok. understood. Let's safely fix the span pb.
Disqus is widely used enough to deserve some non-destructive adaptation on our end.

**Comment by eri-trabiccolo** [comment]
Looks like, there's even another way to achieve the same result, basically the disqus scripts would also look for the `a` elements with an anchor to` #disqus_thread` (basically the comments_link) and will perform the replacement as well.

**Comment by eri-trabiccolo** [comment]
free: fixed in https://github.com/presscustomizr/hueman/pull/762
pro: fixed in https://github.com/presscustomizr/hueman-pro-addons/pull/180

Since this PR acts on CSS and PHP files we can expect:
a) child-theme which override the changed templates to have style issues
b) other style issues due to any server side cache not clean
