### ISSUE TITLE
Remove title attribute "Permalink To" on thumbnails links in post lists

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#763]
https://secure.helpscout.net/conversation/772407723/169913?folderId=607547
> "Permalink To" Blog Post name shows on ToolTip when I hover over blog post
> 
> I want to remove the "Permalink To" text for all posts.

**Comment by eri-trabiccolo** [comment]
Meantime this could be achieved with the localization way (Loco Translate).

**Comment by jtmart** [comment]
Hi, thanks for your great work. It seems that with the latest update of the theme (Hueman Pro 1.4.10) the title attribute "Permalink To" on post list titles is still there on hover. Is there a way to remove the "Permalink To" text for all post titles (.post-title)?
![2021-06-27_100643](https://user-images.githubusercontent.com/51360204/123533070-18d5d100-d730-11eb-9adb-67f915cfb6bc.jpg)
