### ISSUE TITLE
WP comment cookies opt-in checkbox, minor style issue

### ISSUE THREAD

**Issue by eri-trabiccolo** [AlxMedia/hueman#770]
![schermata 2019-02-20 alle 09 23 39](https://user-images.githubusercontent.com/7689242/53077339-0e68f400-34f2-11e9-9664-0df5d027e97d.png)

**Comment by eri-trabiccolo** [comment]
with https://github.com/presscustomizr/hueman/pull/771
![schermata 2019-02-20 alle 09 44 11](https://user-images.githubusercontent.com/7689242/53078390-686ab900-34f4-11e9-8e53-71b282188a9d.png)

**Comment by ghost** [comment]
Great thanks. This was reported by a user right ?

**Comment by eri-trabiccolo** [comment]
Nope, I discovered it because of a support request about the (not) displaying of that checkbox.
Couldn't stand that very bad UI.

**Comment by ghost** [comment]
:D yeah man!
