### ISSUE TITLE
PHP 7.3.2 => PHP Fatal error: Uncaught Error: Invalid serialization data for DateTime object in wp-includes\functions.php:446

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#775]
https://wordpress.org/support/topic/hueman-php-7-iis-error-500/#post-11266214

> WP 5.1, theme version 3.1.14–works fine under my long-standing configuration of PHP 5.3.8. When I attempt to upgrade to PHP 7.3.2, all pages error out with an error 500. So far I’ve:
> 
> – reinstalled WP 5.1
> – deactivated all plugins
> – cleared cache/tried different computer
> – deleted the hueman theme directory and reinstalled fresh copy
> – I was using a child theme but it doesn’t make a difference
> 
> Switching to a different theme with PHP 7.3 (twenty nineteen) and it works fine, so wondering if it’s PHP 7 + hueman in some way. Currently rolled back to PHP 5.3.8 as it currently works. I’d post the system infos, but as I can only access that page on PHP 5 and not PHP 7, seems somewhat pointless.
> 
> Relevant PHP error log:
> [26-Feb-2019 15:23:28 UTC] PHP Fatal error: Uncaught Error: Invalid serialization data for DateTime object in D:\wwwroot\blog\wp-includes\functions.php:446
> Stack trace:
> 0 [internal function]: DateTime->__wakeup()
> 1 D:\wwwroot\blog\wp-includes\functions.php(446): unserialize(‘O:8:”DateTime”:…’)
> 2 D:\wwwroot\blog\wp-includes\option.php(152): maybe_unserialize(‘O:8:”DateTime”:…’)
> 3 D:\wwwroot\blog\wp-includes\option.php(711): get_option(‘_transient_hu_s…’)
> 4 D:\wwwroot\blog\wp-content\themes\hueman\functions\class-utils.php(78): get_transient(‘hu_start_date’)
> 5 D:\wwwroot\blog\wp-content\themes\hueman\functions\class-utils.php(29): HU_utils->hu_init_properties()
> 6 D:\wwwroot\blog\wp-content\themes\hueman\functions\init-core.php(90): HU_utils->__construct()
> 7 D:\wwwroot\blog\wp-includes\template.php(704): require_once(‘D:\\wwwroot\\blog…’)
> 8 D:\wwwroot\blog\wp-content\themes\hueman\functions.php(37): load_template(‘D:\\wwwroot\\blog…’)
> 9 D:\wwwroot\blog\wp-settings.php(479): include(‘D:\\wwwroot\\blog…’)
> 10 D:\wwwroot\blog\wp-config. in D:\wwwroot\blog\wp-includes\functions.php on line 446

**Comment by eri-trabiccolo** [comment]
There's an already opened issue for this. It all started with php7, if you find it there should be a link to an hs ticket with some steps for the users to fix it (requires some knowledge though).

See:
https://github.com/presscustomizr/hueman/issues/549
