### ISSUE TITLE
Author name + published date + updated date in singular => add an option to hide it

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#776]
initially requested here : https://secure.helpscout.net/conversation/795322977/175038?folderId=607547

**Comment by ghost** [comment]
Hello @eri-trabiccolo let's discuss those this issue and this one ( #801 ) tomorrow afternoon if you are available ?

**Comment by eri-trabiccolo** [comment]
Let's do it, but I'll be off starting from 17:30

**Comment by ghost** [comment]
OK roger that.
