### ISSUE TITLE
Possible fatal error when displaying single WooCommerce product when reviews system enabled

### ISSUE THREAD

**Issue by eri-trabiccolo** [AlxMedia/hueman#780]
PHP Fatal error:  Uncaught Error: Call to a member function get_review_count() on string in /srv/www/wordpress-one/public_html/wp-content/themes/hueman/functions/init-plugins-compat.php:217

That's cause at the stage where we display the page (product) title (outside the loop) it seems that the global `$product` is not an object yet but only a string (it's slug).

**Comment by ghost** [comment]
thanks great
