### ISSUE TITLE
Smooth Scroll throwing JS errors in Chrome

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#787]
https://wordpress.org/support/topic/smooth-scroll-throwing-js-errors-in-chrome/#post-11459911

**Comment by eri-trabiccolo** [comment]
Let's see if we can rapidly adapt our "old" code including this fix:
https://github.com/gblazex/smoothscroll-for-websites/commit/155ee594a2e4b43a68b39776706ffd12a99ea54f

**Comment by ghost** [comment]
yep looks good !
