### ISSUE TITLE
Images in headers still don't have image dimensions

### ISSUE THREAD

**Issue by Tarun80** [AlxMedia/hueman#790]
Previously I had an issue about [this very thing](https://github.com/presscustomizr/hueman/issues/300). Unfortunately this issue still exists today.

This is still something that is needed and beneficiary when optimizing a website. Even GTMetrix will flag this as an issue.

What can we do to resolve this?

**Comment by Tarun80** [comment]
Any word on this?

**Comment by Tarun80** [comment]
@eri-trabiccolo @Nikeo Thanks for the patch. Unfortunately this has not resolved the issue. GTMetrix will also report that image dimensions are missing.

```html
<p class="site-title">
    <a class="custom-logo-link" href="localhost" rel="home" title="localhost"><img src="localhost/wp-content/uploads/logo.png" alt="Localhost"></a>
</p>
```

It's still missing the height="##" and width="##"

**Comment by eri-trabiccolo** [comment]
Hi @Tarun80 thanks for the feedback.
So that's a different, yet similar, issue, as https://github.com/presscustomizr/hueman/issues/300 was about the header image not the logo image. 
Opened a new issue about this, see #797
