### ISSUE TITLE
Add new option to control the visibility of featured image in single page 

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#793]
- option should be located in Main body Design > Single page settings
- visibility disabled by default

reported https://secure.helpscout.net/conversation/859696497/217351?folderId=607547

**Comment by eri-trabiccolo** [comment]
Done in #794

though... wouldn't be better to handle the default visibility with the `hu_started_before_version`, considering that the featured image in pages is currently displayed by default?

**Comment by ghost** [comment]
@eri-trabiccolo thanks for the PR
About the defaut value, I'll communicate about the change in the release note + a quick doc.
Hardcoding the default is not risky and I prefer that users know about this option. In other words, if they don't see the featured image as it was usually, they'll discover that they can now display it or not.

**Comment by eri-trabiccolo** [comment]
Makes sense, thanks for the explanation :)
