### ISSUE TITLE
Allow widgets files to be overridden in child themes

### ISSUE THREAD

**Issue by eri-trabiccolo** [AlxMedia/hueman#798]
Reported:
https://wordpress.org/support/topic/hueman-alx-posts/

It would mean using `locate_template(filename,$load=true)` here:
https://github.com/presscustomizr/hueman/blob/dev/functions/init-sidebars-widgets.php#L4-L6

**Comment by ghost** [comment]
@eri-trabiccolo  I did not test yet but can you confirm that using `locate_template` instead of `load_template` would be enough ?
thanks

**Comment by ghost** [comment]
( I'm about to push a new release of Hueman and would like to include this improvement in it )

**Comment by eri-trabiccolo** [comment]
Yes, this way:
```
/*  Loads Custom Widgets
/* ------------------------------------ */
locate_template( 'functions/widgets/alx-tabs.php', true );
locate_template( 'functions/widgets/alx-video.php', true );
locate_template( 'functions/widgets/alx-posts.php', true );
```
(or)
```
/*  Loads Custom Widgets
/* ------------------------------------ */
locate_template( array( 'functions/widgets/alx-tabs.php',  'functions/widgets/alx-video.php', 'functions/widgets/alx-posts.php')  , true );
```
