### ISSUE TITLE
The theme customization gets reset all the time

### ISSUE THREAD

**Issue by mayazir** [AlxMedia/hueman#807]
Hi, I already wrote here a few times, but the problem is still presented. I understand this is a free theme, but I spent more than 2 years in making my site and adapt all to Hueman theme and I have the same problem sometimes each month, sometimes every 2 weeks.. I have to check the site each day, a few times a day, better each hour.. And I can fix the problem just if I am in front of my PC and if not then my site looks awful until I customize it again.. And ZERO help.
Author, pay attention, there is something to do with this bug.
Ok, the site is [MexicanRoutes.com](url) and sometimes all Theme Customization gets reset by default.
I don't talk about CSS style, I mean Theme Customization.
Check my site now and look at these screens I made when it got reset again...
The only way to fix is to customize it again all...
All plugins I use I use them with the rest of my sites and have no problem..
I also use the same Theme with a few more sites and they also sometimes get reset.
But MexicanRoutes.com gets reset much more than the rest of my sites, I have just 1 conclusion, maybe it has something to see with DB? I caught the site a few times disconnected from DB, it happens when there are too many queries per hour and my host lost the connection with DB and 1 hour later it connected the DB again... But I also got DB issue but the site was ok, so it's not DB...
Anyway, check these screens: 
https://mexicanroutes.com/screen-1.jpg
https://mexicanroutes.com/screen-2.jpg
https://mexicanroutes.com/screen-3.jpg
And now check my site now... You see all sidebar header color get reset by default, header gets reset by default, in single post appear forward and backward arrows..
Sometimes it happens twice in a week, sometimes once in a month..

**Comment by mayazir** [comment]
I will add some more thoughts...
Check this: https://mexicanroutes.com/screen-2.jpg
Ok, you can say, add footer color into CSS style.. ok, but the problem is not just the color..
You see the footer widgets are gone, also are gone contact icons on the left sidebar header...
So its not just CSS... all the theme gets reset to default..

**Comment by mayazir** [comment]
It happened again... ok, I use the plugin to restore Theme Customize option in a few clicks, but:
1. I need to be in front of PC to fix it.
2. I need manually to add Contact us and Facebook links to the left sidebar header.
3. I need to check the site every hour.. the rest of my life

**Comment by ghost** [comment]
Hi, I remember your previous issues. 
I understand your concern and frustration. But there's no need to open new issue each time for the same problem.
- https://github.com/presscustomizr/hueman/issues/600
- https://github.com/presscustomizr/hueman/issues/710
- https://github.com/presscustomizr/hueman/issues/740

We've already tried to help and reproduce the problem in the past, without success unfortunately.
 ( be kind and don't say _ZERO help_ please, thanks ).

As you said, the theme is free to use. We are working hard to fix bugs and problems for our users. But we need to be able to reproduce the problem and understand it. About your problem, we're not able to reproduce it and state if this is related to the theme itself or not for the moment.

Thanks for reporting the problem. We will discuss it during our next developer chat.

**Comment by mayazir** [comment]
I mean zero help from all the source I was asking for... Ok, better say zero solution.
I talked to hoster, to you, I asked a few friends.. I don't know when it happened..
I have 4 websites with this theme:
AncientMayanRuins.com
MexicanRoutes.com
TravelSpain.info
FantasticRoutes.com
The site with the most traffic is MexicanRoutes - 50-60 daily + bots and crawlers.
My query limit is more than enough to host these sites, Ok maybe MexicanRoutes sometimes gets more queries, but... really..with just 50-60 daily visits as much?
But ok, AncientMayanRuins with a few daily visits also got reset a few times in past..
Query limit? Impossible...
TravelSpain had the same issue a few times and it had no traffic still..
But MexicanRoutes.com has it every X time, it could be once a month, once a week, twice a week, twice a month..
**Ok, could you say how could I make the default Customize config with Contact details and widgets etc?
I pay if you consider it paid support.. I don't want a paid version, I like this one, but I can pay if you help me edit .php**

**Comment by hosseinfarnia** [comment]
Hi @Nikeo 
I think the best solution is adding an option for exporting and importing the settings. In this way if the theme gets reset, we can import the previous saved settings.

This may happen for any theme because of so many customizations and plugin conflicts and even different hosts. It's out of your control.

**Comment by mayazir** [comment]
> 
> 
> Hi @Nikeo
> I think the best solution is adding an option for exporting and importing the settings. In this way, if the theme gets reset, we can import the previously saved settings.
> 
> This may happen for any theme because of so many customizations and plugin conflicts and even different hosts. It's out of your control.

I use the plugin to restore quickly all settings, but I never know when it happens so I have to check the site every hour.. 
I see just 1 solution for me... to use modified DEFAULT settings.. I mean replace the default Hueman settings by my own settings, but I don't know where is all these code lines..
Actually, default settings have no widgets in the footer, had no contact details in the header of the left sidebar etc.. I need to replace these settings by my own.. But this is a temp solution.

**Comment by mayazir** [comment]
well, it happened again.

**Comment by mayazir** [comment]
the same thing happened again.
and this time not just to mexicanroutes.com but also to ancientmayanruins.com

**Comment by hosseinfarnia** [comment]
Hi @mayazir
I took a look at your websites.
I think you've done so many heavy customizations. That's not normal for this theme.
or it may be a plugin conflict.
I recommend you to change your theme. Something which can be customized from zero to one hundred, like Divi theme.
Hope it helps.

**Comment by mayazir** [comment]
> 
> 
> Hi @mayazir
> I took a look at your websites.
> I think you've done so many heavy customizations. That's not normal for this theme.
> or it may be a plugin conflict.
> I recommend you to change your theme. Something which can be customized from zero to one hundred, like Divi theme.
> Hope it helps.

The site is not heavy customized.
99% is just CSS.
There are also some plugins which I am 100% sure they work just fine, I use them on my other sites.
And I also don't have too many plugins as you think..

**Comment by mayazir** [comment]
the same again...

**Comment by mayazir** [comment]
The same happened again with FantasticRoutes.com my another site.
The only customization I make is **style.css**
