### ISSUE TITLE
Classic Grid => Allow a 1 column layout

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#811]
requested here : https://secure.helpscout.net/conversation/906332257/218057/

- customizer setting to modify : max number of columns => Add 1 in the list
- img size => use existing size for featured post ?

**Comment by ghost** [comment]
Hello @eri-trabiccolo do you think you'll have time to push this PR in the coming days ?
Thanks

**Comment by eri-trabiccolo** [comment]
Hi Nico,
sorry for the very big delay on this.
I'm on it right now.

**Comment by ghost** [comment]
Great thanks
I have informed the user about it : https://secure.helpscout.net/conversation/950830476/218561/ ( user sent a reminder today ... )

**Comment by eri-trabiccolo** [comment]
@Nikeo we forgot that the classic grid actually has no option to select the number of columns.
I can add an option that will be visible only when using the classic grid which says something like:
Display your posts in one column.

where there are those other two options:
![Schermata 2019-09-09 alle 10 40 56](https://user-images.githubusercontent.com/7689242/64516842-74329700-d2ef-11e9-8bf1-9c84e620b5bf.png)

**Comment by ghost** [comment]
yes in the free. but we have the option in pro.
@eri-trabiccolo this could be messy to add an option in free, and have another one in pro.
Let's consider adding the one column to pro only, what do you think ?
![2019-09-09_11-05-53](https://user-images.githubusercontent.com/3038156/64518111-e1472c00-d2f1-11e9-989b-e3fb362d4d63.jpg)

**Comment by eri-trabiccolo** [comment]
Yes you're right, and yes pro only.
The number of columns, though, is shared among classic and masonry, so let's allow a masonry of 1 column too.

**Comment by eri-trabiccolo** [comment]
PR in HAP at https://github.com/presscustomizr/hueman-pro-addons/pull/196
