### ISSUE TITLE
lazy load conflict in chrome browser

### ISSUE THREAD

**Issue by hosseinfarnia** [AlxMedia/hueman#818]
Hi @Nikeo and @eri-trabiccolo 
After the release of the latest chrome browser, lazy load is automatically supported and activated by chrome:
chrome://flags/#enable-lazy-image-loading
When lazy load is activated in both chrome and hueman theme, Thumbnails are not shown.
So I deactivated lazy load in hueman theme to solve the issue.
I think there is a conflict between them.
Thanks

**Comment by eri-trabiccolo** [comment]
Hi hosseinfarnia,
I'm not able to reproduce your issue. Or better, the chrome lazy load feature says:

> Defers the loading of images marked with the attribute 'loading=lazy' until the page is scrolled down near them. – Mac, Windows, Linux, Chrome OS, Android

So, unless you (or plugins) add that attribute `loading=lazy` chrome feature won't be triggered, so no conflict. Of course if you choose to use that attribute you're choosing to use the chrome feature and not the native theme(s) feature, hence you have to disable it.

Thanks.
