### ISSUE TITLE
Additional updates required for Option tree when running Theme Check plugin

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#820]
following #815 , some new warnings are displayed when running theme check
 
![2019-08-27_19-21-52](https://user-images.githubusercontent.com/3038156/63793921-f5a62480-c900-11e9-91e7-d31b6261b268.jpg)

**Comment by eri-trabiccolo** [comment]
I'm sorry for this.
I guess I missed this "removal" because was not part of the history of that directory here on github... right?!

**Comment by ghost** [comment]
yes probably. not a problem don't worry!
