### ISSUE TITLE
The mobile menu doesn't automatically close when clicking on an link item

### ISSUE THREAD

**Issue by eri-trabiccolo** [AlxMedia/hueman#830]
This can be annoying when using links to targets in the same page.

Reported here:
https://wordpress.org/support/topic/mobile-menu-does-not-close-automatically/

**Comment by ghost** [comment]
Hi @eri-trabiccolo I tested the issue. I don't really find it annoying to navigate the various anchor of the page with the submenu open. A quick mouse move makes it vanish anyway. Or maybe in your test it stays open all the time ?

**Comment by eri-trabiccolo** [comment]
The mouse in mobile? :D 
I know I know, you mean triggering a scroll, yeah I see what you mean, not sure I think we can close it on clicking a valid target.

**Comment by ghost** [comment]
Well, I totally missed the "mobile" part.... which was actually the title of the topic...So now I got the point.
Feeling like Donny ( "shut the fuck up donny" )
