### ISSUE TITLE
Feature reqest: Color address bar in Chrome for Android

### ISSUE THREAD

**Issue by Dan-Danielson** [AlxMedia/hueman#833]
Please, could you add this code in header.php file just before the closing `</head>` tag:

`<meta name="theme-color" content="#ff6600" />`

This simple line allows to change color of address bar in Google Chrome for Android.

(The hardcoded color is just an example, it should be implemented in a way so it is available to edit in WP Theme Customizer).

Thanks a lot!

**Comment by hosseinfarnia** [comment]
Hi, @Dan-Danielson 
Install this plugin:
https://wordpress.org/plugins/browser-theme-color/
