### ISSUE TITLE
Latest chrome and a 3 columns content middle layout, make the horizontal scrollbar appear.

### ISSUE THREAD

**Issue by eri-trabiccolo** [AlxMedia/hueman#834]
This is pretty annoying.
I couldn't reproduce it with a previous chrome version (77.*).
Nor I can with the latest firefox (70).
(both on a mac) 

I think is a chrome bug.
It has to do with the positioning of the right sidebar, but the CSS is correct IMHO.

We can temporarily patch this adding the following CSS
`.col-3cm {overflow-x: hidden}`

reported here:
https://wordpress.org/support/topic/maybe-a-css-issue-please-check-it/#post-12075180

**Comment by ghost** [comment]
OK. Yes pretty annoying !
Let's apply this patch then. I will try to report the bug to chrome devs

**Comment by ghost** [comment]
I'll add the patch to the next release.

**Comment by ghost** [comment]
Also reported here:https://wordpress.org/support/topic/strange-scrool-bar-at-the-bottom-in-chrome/
New release today
