### ISSUE TITLE
Header's height + post layout broken => resizing fixes the problem

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#839]
Occurs only on articles.
I can reproduce the problem on **Firefox.**

Reported here : https://secure.helpscout.net/conversation/1025603766/219533/

![2019-12-09_08-40-46](https://user-images.githubusercontent.com/3038156/70416751-0ae23180-1a60-11ea-86c0-0c913cdb1701.jpg)
![2019-12-09_08-40-31](https://user-images.githubusercontent.com/3038156/70416752-0ae23180-1a60-11ea-8abb-5e627138e1e1.jpg)

@eri-trabiccolo can you take a look if you have time in the coming days ?
Thanks !

**Comment by ghost** [comment]
**resizing the window fixes the problem.**

I've asked the user to follow the usual troubleshooting steps.

Testing with the same logo and page layout could help.

Idea : this might be due to logo image load time. Since we can't control this => hack this issue by triggering several page resize during the first n seconds after page load ?

**Comment by eri-trabiccolo** [comment]
@Nikeo 
I cannot reproduce the issue on my local website... using the user's logo and layout
You know what I might try with an heavy image though.

Anyway we can listen for the logo image to be loaded, the same way we listen to the header-image...
https://github.com/presscustomizr/hueman/blob/v3.4.33/assets/front/js/_parts/_main_userxp_2_stickify.part.js#L56

**Comment by ghost** [comment]
I've implemented your idea for the logo image + several automatic resize events on pageload. A bit hacky but ensures a correct header height
