### ISSUE TITLE
Use the child-theme version when enqueueing its style

### ISSUE THREAD

**Issue by eri-trabiccolo** [AlxMedia/hueman#860]
reported https://secure.helpscout.net/conversation/1099713154/220372?folderId=607709
I think it makes sense, and would mean, that here:
https://github.com/presscustomizr/hueman/blob/v3.4.39/functions/init-front.php#L1272
instead of the `HUEMAN_VER` constant we should use:
`            ( defined('WP_DEBUG') && true === WP_DEBUG ) ? time() : get_stylesheet()->version,`

**Comment by ghost** [comment]
yep agree

**Comment by eri-trabiccolo** [comment]
@Nikeo bump
are we going to release this improvement soon?

**Comment by eri-trabiccolo** [comment]
Hi @Nikeo 
we fixed this the wrong way.

Since I proposed I wrong fix here but did it correctly on my local install I'm going to push a PR.
