### ISSUE TITLE
[performance][srcset attribute] => limit browsers choice for srcset on high resolution device

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#866]
otherwise the browser might pick a too large size available in srcset
https://wordpress.org/support/topic/weird-issue-displayed-image-sizes-in-disagreement-with-hueman-documentation/

https://secure.helpscout.net/conversation/1107155999/220473?folderId=607541

> **Problem: Small images/thumbnails are displayed using very (i.e. unnecessarily) high-resolution versions, while the big featured post image near the top uses a lower-resolution version. It makes no sense, plus it is in disagreement with the theme’s documentation.**

Temporary solution => generate retina sizes + add retina sizes to srcset with this plugin : https://wordpress.org/plugins/wp-retina-2x/

**Long term solution** => explore a fine grained implementation
- **use max_srcset_image_width to limit available sizes in srcset attribute**
- https://make.wordpress.org/core/2015/11/10/responsive-images-in-wordpress-4-4/
- https://alistapart.com/article/responsive-images-in-practice/

**Comment by Nikeo** [comment]
User finally fixed the problem
