### ISSUE TITLE
Menu and category error after WordPress 5.4 update ?

### ISSUE THREAD

**Issue by ghost** [AlxMedia/hueman#875]
> I did update to WordPress 5.4 update yesterday and after the update I got errors about my categories (outdated) and items in my menu (outdated). Both on mobile and on pc.
> 
> I was able to roll back the update, so fine for now. Any idea what the problem can be?
> 
> I use Hueman theme latest free version.

https://wordpress.org/support/topic/menu-and-category-error-after-wordpress-5-4-update/#post-12615592

**Comment by ghost** [comment]
Hello @eri-trabiccolo, can you check on your side when you'll have the time ?
Thanks, 'good day!

**Comment by eri-trabiccolo** [comment]
Just tried to reproduce it no luck, I honestly don't understand the actual issue.
Even a screenshot might be useful, let's wait, if it's a real issue we'll see other tickets of this type :/

**Comment by ghost** [comment]
Thanks.
Yes, I've requested more information from the user in the support topic.
