### ISSUE TITLE
slider not showing in RTL after update to 3.5.3

### ISSUE THREAD

**Issue by hanyseyedy** [AlxMedia/hueman#878]
hi,
i'm using free version of theme.
Unfortunately home page slider not showing in last update.
my site is rtl and I don't know if this problem exists in the "LTR" mode or not.
Because of this problem, I returned the theme to the previous version.
please solve this issue.

thanks a lot

**Comment by ghost** [comment]
Hi thanks for opening this issue @hanyseyedy 
The problem has been fixed here https://github.com/presscustomizr/hueman/issues/884 in the latest version of the theme.
Let me know if you're still having problems.

**Comment by hanyseyedy** [comment]
hi Nicolas
how are you

I followed up on this issue through the hueman website.
Fortunately, they solved the problem.

Thank you very much for your follow-up
