### ISSUE TITLE
iPhone safari/iOS 8 issue: Menu sometimes won't expand on single posts/pages

### ISSUE THREAD

**Issue by AlxMedia** [AlxMedia/hueman#88]
The menus won't expand, and if flipped into landscape mode the toggle sidebars will not work properly either.
iPhone menu issue: https://wordpress.org/support/topic/navigation-menus-stop-working-on-iphone?replies=8
iPad sidebar issue: https://wordpress.org/support/topic/bug-sidebars-not-opening-in-safariios-even-on-alexanders-own-demo-site?replies=5 (update: fixed now)

The issues are inconsistent and weird, so I could really need some help here on this one.

**Comment by AlxMedia** [comment]
The only thing I can find that is consistently working is Anew, on same devices, using the same Javascript in scripts.js: http://demo.alxmedia.se/anew/ - which makes this even more weird.

**Comment by AlxMedia** [comment]
The javascript seem to inconsistently lock down. I managed to get it from frozen to unfrozen and working by clicking on next on a flexslider slideshow within a post, and viola, menus, sliders and sidebars works fine again.

**Comment by KaiserStudios** [comment]
I switched over to Anew and am having the same issue right off the bat with the flyout menus.

<a href="http://shootsharper.com">ShootSharper.com</a>

Hope this helps.

Thanks for looking into this!

**Comment by KaiserStudios** [comment]
![screen shot 2015-01-31 at 9 54 07 am](https://cloud.githubusercontent.com/assets/10786123/5988658/2bbc8ede-a92f-11e4-9098-8d58135b1ccc.png)
![screen shot 2015-01-31 at 9 28 18 am](https://cloud.githubusercontent.com/assets/10786123/5988659/2bd0b04e-a92f-11e4-9541-2953c42fcbab.png)
![screen shot 2015-01-31 at 9 26 29 am](https://cloud.githubusercontent.com/assets/10786123/5988660/2bd0f5c2-a92f-11e4-888a-7668a460763d.png)

Plugged my iPhone in and ran the web inspector.  Not really a code person but maybe this will be helpful.

After doing a few test it seems if I dump all the website data in my iPhone settings page for my URL I get functional back on the expandable menus until i go into a single post then it breaks again.

**Comment by elliot-labs** [comment]
Is this issue present on Android devices?

**Comment by AlxMedia** [comment]
Nope, all works fine on Android in default browser, Chrome, Firefox and Opera.

It has been working on iPad as well, so it may be some new iOS 8 issue.

**Comment by elliot-labs** [comment]
Hmmm...

On Tue, Feb 3, 2015 at 2:44 AM, Alexander Agnarson <notifications@github.com
> wrote:

> Nope, all works fine on Android in default browser, Chrome, Firefox and
> Opera.
>
> It has been working on iPad as well, so it may be some new iOS 8 issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AlxMedia/hueman/issues/88#issuecomment-72607720>.
>



-- 

Elliot

DISCLAIMER:
This e-mail is for the intended recipient(s) only

If you have received it by mistake please let me know by reply and then
delete it from your system; access, disclosure, copying, distribution or
reliance on any of it by anyone else is prohibited.

If you as intended recipient have received this e-mail incorrectly, please
notify the sender (via e-mail) immediately.

**Comment by AlxMedia** [comment]
The issue can not be recreated on any other device, other than iPad and iPhone with iOS 8, as far as I can see.

**Comment by AlxMedia** [comment]
Step 1: Go to http://demo.alxmedia.se/hueman/
Step 2: Click on "Take a Deep Breath". Now click on sidebar. Won't work.
Step 3: Click on next/prev on the slider. Now click on sidebar. It works!

Or:
Step 1: Go to http://demo.alxmedia.se/hueman/
Step 2: Click on a non-slider post. Now click on sidebar. Won't work.
Step 3: With no flexslider, there is no way to unfreeze the thing that goes on, so it remains broken.

**Comment by AlxMedia** [comment]
At last I've found something, it's Safari's bad compatibility with CSS3 transitions it seems, combined with some weird CSS width issue:
Try adding this in custom.css:
`
@media only screen and (min-width: 480px) and (max-width: 1200px) {
.s2 { min-width: 50px; max-width: 50px; width: auto; }
.s2-expand .s2 { min-width: 260px; max-width: 260px; width: auto; }
}
@media only screen and (min-width: 480px) and (max-width: 960px) {
.s1 { min-width: 50px; max-width: 50px; width: auto; }
.s1-expand .s1 { min-width: 340px; max-width: 340px; width: auto; }
}
`
This will remove the slide-out transition, but the sidebars will start working on iPad.

**Comment by AlxMedia** [comment]
@zgambleholmes I completely missed your replies! I'm going to test it right away.

**Comment by AlxMedia** [comment]
```css
@media only screen and (max-width: 719px) {
.safari .nav-wrap.transition { -webkit-transition: none; transition: none; }
}
```
Is enough for the iPhone menu fix.
