### ISSUE TITLE
How to change page title format?

### ISSUE THREAD

**Issue by olword** [AlxMedia/hueman#882]
Hi, 
Currently show page title is "`<article name> - <site name>`". But I want  "`<article naeme> | <site name>`". Where should I change the code?

**Comment by olword** [comment]
Previously my site used this format. After I changed my template all site's titles was changed that is not really good.
Is it ok to use  | and in what file can I edit it?
I tried to find but was not success.

**Comment by ghost** [comment]
Hi @olword,
We use github to organize the development's isssues and pull requests of the theme. No assistance for devs is provided here.
If you have questions or requests about the theme, please use the theme's forum : https://wordpress.org/support/theme/hueman/
Thank you.
