### ISSUE TITLE
File 'package-lock.json' is removed in 3.4.0-beta

### ISSUE THREAD

**Issue by machitgarha** [AlxMedia/hueman#887]
This is not related to the theme itself, and maybe this is not a really important issue. However, I'm aware of the removal of the `package-lock.json` in 7928a95f59d54fc442f10d9e8a618ba664152698. The lock file should not be removed, as stated [here](https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5) and [here](https://github.com/npm/npm/blob/v5.0.0/doc/files/package-lock.json.md#description).

First, I want to the reason of the removal, and, ask you to track it back to the VCS.

Thanks.

**Comment by ghost** [comment]
Thanks for reporting this problem.
