### ISSUE TITLE
featured posts slider not working with Polylang in Arabic

### ISSUE THREAD

**Issue by ammarfalih** [AlxMedia/hueman#949]
for multilingual websites using Polylang, featured posts slider stopped working in the Arabic language since version 3.6.1 because of the removal of the CSS property ( display: none ) of the class ( .flexslider .slides > li ), when added manually to the file the website works fine again in the Arabic Language ( and maybe to the other RTL languages ).
Tested with the browser ( Google Chrome )

**Comment by ghost** [comment]
OK thanks for reporting the problem.
Exploring a fix
