### ISSUE TITLE
Contact form 7 dropdown style

### ISSUE THREAD

**Issue by KardiWeb** [AlxMedia/hueman#97]
Hello!

How to styling contact form 7 plugin dropdown lists?

![snapshot11](https://cloud.githubusercontent.com/assets/842504/6334977/563fcdb2-bb98-11e4-8797-4525a0f40ef8.png)

**Comment by Jack0r** [comment]
You might be looking for this:
http://contactform7.com/checkboxes-radio-buttons-and-menus/

**Comment by AlxMedia** [comment]
Fixed in the next update. Thanks for reporting!
