### ISSUE TITLE
Malware..?

### ISSUE THREAD

**Issue by dbudd99** [AlxMedia/hueman#986]
I ran a malware scan today on my WP site today.....Big red warning came up....in the Hueman Theme

widget_zone_module.php was the offender

When it was Quarantined the site crashed....I switched WP to a default theme and its back.

Downloaded a fresh copy of the theme from wordpress.com and in that file is the widget_zone_module.php.

Compared the two and I don't see any difference....

Whats up?? I have to switch themes or is a older version of Hueman from this site ok to use??

THX

**Comment by giorgioriccardi** [comment]
There is no `widget_zone_module.php` file in this project.
Likely you have an issue unrelated specifically to the theme but maybe a broader/larger problem with the hosting/site/registrar ...

**Comment by dbudd99** [comment]
hueman.3.7.23/hueman/functions/czr-modules/widget-zones/widget_zones_module.php

Hueman  Version: 3.7.23

Last updated: August 25, 2022

I just downloaded it again...what am I see then??? straight from https://wordpress.org/themes/hueman/

**Comment by giorgioriccardi** [comment]
did you try to run a wordfence scan on your site?

**Comment by dbudd99** [comment]
all scans I had been running came back clean except the 
Anti-Malware Security and Brute-Force Firewall
it flaged that file as a threat.
I emailed the author of the plugin and he just responded that the file looks good to him and he has updated his definitions for his plugin and white flagged that file.
I guess it was good all along..
since 70,000 copies on the web..I'm surprised this wasn't an issue before..
Thanks for helping me out...

DB

http://photorecon.net 

    On Tuesday, June 13, 2023 at 06:00:28 PM PDT, Giorgio Riccardi ***@***.***> wrote:  
 
 


did you try to run a wordfence scan on your site?

**Comment by giorgioriccardi** [comment]
`I emailed the author of the plugin and he just responded that the file looks good to him and he has updated his definitions for his plugin and white flagged that file.` better safe than sorry!

Thanks for being so thorough with a potential issue. Feel free to close the issue.
Cheers

**Comment by dbudd99** [comment]
Determine all is well with the file....not malware....closing this..
